### ISSUE TITLE
OpenMRS admin account get locked  therefore login authentication failed from app and other clients.

### ISSUE THREAD

**Issue by sohelsarder** [OpenSRP/opensrp-server#104]
Admin account of openmrs instance at Bangladesh site get locked frequently and the workers facing frequent disturbance while they are attempting log in opensrp app. This is because authentication service at openmrs not worked in that time.

**Comment by cagulas** [comment]
@maimoonak do you have any incite on this?  I know I had asked you a similar question not too long ago, and you had recommended creating a new login with admin permission level.  Should they do the same here?

**Comment by sohelsarder** [comment]
I think i just figured it out it was schedule tracker module which expected admin user name and password in its global properties, it was trying its default which was incorrect in our instances and throwing exceptions,

WARN - AuthenticatedTask.authenticate(87) |2015-12-11 23:55:27,821| Not authenticating to avoid locking account. Please ensure you scheduler username and password are configured correctly in your global properties

I just changed it to our correct credentials, i guess this should resolve the problem.

**Comment by maimoonak** [comment]
@sohelsarder also make sure that  user credentials in opensrp.properties for openmrs are not admin..
