### ISSUE TITLE
PSRF- Mother-Child Concept 

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-server#106]
While we can see the parent/child concepts for the vaccine group are working in the PK xlsform, the parent/child concepts in one of the BD xlsforms are not working.

Here is the form:  https://docs.google.com/spreadsheets/d/1jQ3o5y6DKOvhVUvHPbR_YrxwdGw5089F8A5E6QsbKHk/edit#gid=73317944

In rows 52-55, the parent concepts are all datatype of NA, and the child concept used in all of them is datatype Coded.  

In OpenMRS, you can see these fields are showing up with just the parent concept and no child concept answer showing.

When you click on one of these concepts, you get the following screen (it looks like it's trying to use the NA parent concept as the question concept).

FYI, in the PK xlsform, the parent concept is datatype of Coded, and child concept is datatype of Date, which is different from BD xlsform. the datatype of BD form is N/A.

@cagulas @sohelsarder @asifur77

**Comment by maimoonak** [comment]
xlsform/model.xml has alot of issues with concept mappings.

"concept": "163092AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"value": "3"
Boolean cannot recognize value 3

"concept": "163091AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"value": "2"
Boolean cannot recognize value 2

"concept": "163088AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"value": "1"
Coded question can not have value 1

concept 162594AAAAAAAAAAAAAAAAAAAAAAAAAA is missing last AAAs

Same issue with 148834AAAAAAA.......

Same issue with 1729 and all parent concepts

Once resolved issues in form submission it shows data correctly
http://46.101.51.199:8080/openmrs/admin/encounters/encounter.form?encounterId=1503

**Comment by asifur77** [comment]
Hi thanks for your reply we did correct according to your suggestion. We are now sending 0/1 for boolean case. It is accepting but regardless of 0/1 in these concept we are always finding 'false' in openmrs against these observation. Can you please say what is reason for this?

"concept": "163092AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"value": "1"

"concept": "163091AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"value": "0"

**Comment by maimoonak** [comment]
I double checked with multiple value and found that it doesnot accept 1 as
true. This strange and may be a bug in OpenMRS. A quick solution is to send
true and false instead of 0/1. In the meanwhile we can try connecting with
OpenMRS community.

**Comment by cagulas** [comment]
Closing this.  Values 0/1 are now supported in REST web services.
