### ISSUE TITLE
openSRP server don't have log of  submission receive time  

### ISSUE THREAD

**Issue by sohelsarder** [OpenSRP/opensrp-server#107]
Currently after receiving each submission server don't keep record of submission receive time in database. So there is no way of tracing when server received that submission and what was transmission delay or after collection how long front line health worker took to forward submission to server.

**Comment by cagulas** [comment]
@sohelsarder on the tech call, it was suggested you use serverVersion that is attached to form submission when it gets sent to server.  Did you check to see if this could be used for this purpose or not?  

@numeranazneen

**Comment by sohelsarder** [comment]
@cagulas  server Version conversion really works fine,  if we ignore conversion cost each time . In fact we did tested and planned that conversion will placed at dashboard side for the time being while it displays data. Permanent Key for it in couch doc we might consider later.

Thanks all for your help and participation.
