### ISSUE TITLE
OpenSRP Schedule Visualization Dashboard 

### ISSUE THREAD

**Issue by sohelsarder** [OpenSRP/opensrp-server#109]
Currently  after schedule generation by MoTech engine there is not much visibility of all schedules at a glance and not even trace of total version of it through out the time (actions have the last snap only). Although each provider has its access to their own schedule from TAB but if some one want to find them all there is no single point of it. Which is important for clients (i.e all provider supervisor who is interested to see which provider busy with what) to get the insight of all providers activities so that he/she can follow up or change the priority if he/she wants. 
One possible solution could be,
1. Schedule data transmission to openMRS by help of  openmrs schedule tracker module and grab that view from there.
2. Generate ScheduleLog in openSRP couchDB   and keep transmission with openMRS as well.  So if transmission broken with openMRS we can get it from its primary source couchDB. Along with it if someone want to generate the whole report from openSRP not using openMRS they might have that options as well.

**Comment by sohelsarder** [comment]
Data generated in couchDB scheduleLog table and that can be visualize from BD openSRP site dashboard, can be filtered by provider, schedule status and schedule date.

**Comment by cagulas** [comment]
Sounds like great work here. If possible, it would be great to see a quick demo of the scheduling on the dashboard in this week's tech call.

cc @maina @keymane
