### ISSUE TITLE
Move form logic to opensrp-core

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#11]
Move opensrp-form to opensrp-core.
- It is not acting as an independent, self-contained module.
- It is a part of core opensrp and we donot want to remove it ever from system
- @sohelsarder suggested something to make it extensible to be integrable with odk or other external apps (in future)..... Needs more clarification on this..
- Could we ever have data for any one without a FormSubmission? Would there be any provision for this?

@mberg , @alihabib , @raihan-mpower , @julkarnain , @ndisha

**Comment by ndisha** [comment]
@sohelsarder @maimoonak @koros what direction have we taken on this? Its probably done so please update the issue with the solution and close?

**Comment by maimoonak** [comment]
We haven't made this change yet. This is not a priority and may be affected
by our new strategy for data syncing. That's why it's either rejected or
something to look into V3

**Comment by maimoonak** [comment]
Rejected!! because nobody finds it useful and form module now has been extended to handle form parser logic
