### ISSUE TITLE
Shared health record (SHR) integration with openSRP through SHR client module of openMRS 

### ISSUE THREAD

**Issue by sohelsarder** [OpenSRP/opensrp-server#110]
We already have bit insight of SHR and already have covered basic interaction with SHR through rest service client. Above all currently we are getting data into openMRS. Now we need to build integration with SHR from opeSRP openMRS instance.

SHR insight:
https://sharedhealth.atlassian.net/wiki/display/docs/MCI+Patient+API
SHR client module:
https://github.com/SharedHealth/openmrs-module-bdshrclient

**Comment by julkarnain** [comment]
@maimoonak @koros @sohelsarder  If any one can help me to make understanding 
openmrs-atomfeed module https://github.com/ICT4H/openmrs-atomfeed
 and 
atomfeed module https://github.com/ICT4H/atomfeed

These two modules are used in Bhamni as well as in Shared Health Record

**Comment by sohelsarder** [comment]
This integration has done and tested with bahmniMRS using bdSHR client module. preparation ongoing for production deployment.
