### ISSUE TITLE
Process alerts using EC model

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-server#116]
Modify process alerts server side functionality to process alerts from the EC model data

**Comment by maimoonak** [comment]
Alerts are already been generated from CE model.

**Comment by maina** [comment]
Thanks @maimoonak, could you point us the code that's doing this or the JUnit tests for this.

**Comment by maimoonak** [comment]
https://github.com/OpenSRP/opensrp-server/blob/v2/opensrp-core/src/test/java/org/opensrp/repository/it/FormLifeCycleTest.java

**Comment by maina** [comment]
@maimoonak I see... when does the process alerts functionality get invoked since sync is handled by cloudant which never goes through the controllers?

**Comment by maimoonak** [comment]
It is based on FormSubmission processing which is a scheduled task. Not based on any event

**Comment by maina** [comment]
I thought we'll no longer be having FormSubmissions when we move to the CE data model?

**Comment by maimoonak** [comment]
Ohk... But are you working on converting xlsform to CE model. I remember we discussed to keep formSubmissions as well to keep audit log. Current EC model also maps to formSubmissions. Could you please share the architecture diagram of what we are trying to do?

**Comment by maimoonak** [comment]
Ohk... But are you working on converting xlsform to CE model. I remember we discussed to keep formSubmissions as well to keep audit log. Current EC model also maps to formSubmissions. Could you please share the architecture diagram of what we are trying to do?

**Comment by maina** [comment]
I can't recall but since we've a tech call today, we can discuss it further.

**Comment by maina** [comment]
![alerts](https://cloud.githubusercontent.com/assets/360650/17735552/87115c06-648b-11e6-86a0-2bf4f4d0a656.png)
