### ISSUE TITLE
Data migration for existing form submissions data to EC model

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-server#117]
Extending the existing logic in the server side code v2 branch, implement functionality that will convert existing form submissions in the couchdb to EC data.

**Comment by maina** [comment]
@maimoonak @sohelsarder , am getting this error when processing a bunch of Bangladesh form submissions to EC data in the server side: **Multiple clients with identifier type GOB HHID and ID 9999 exist.
at org.opensrp.service.ClientService.findClient(ClientService.java:120)**
I guess this check should be relaxed since in case of Bangladesh household registration, when the GOB_HHID value is unknown, it’s set to 9999 meaning multiple records would share this value
what do you think?

**Comment by sohelsarder** [comment]
@maina yes you are right, validation should be relaxed for that case. GOB_HHID is not unique identifier for a client it could be repeat for different client live in different area.

**Comment by maimoonak** [comment]
if any variable is mapped as person_identifier it has to be unique ... openmrs & srp donot allow duplicates in patient identifier so if a value is non-unique it should not be marked a identifier rather choose person_attribute for such cases

**Comment by cagulas** [comment]
Thanks everyone, GOB HHID and JiVita HHID are not marked as person_identifiers, but rather, person_attributes, so all is well.
