### ISSUE TITLE
Modification in team management moudle to make it workable with Bahmni-MRS

### ISSUE THREAD

**Issue by sohelsarder** [OpenSRP/opensrp-server#119]
BahmniMRS maintain address hierarchy different way than core OpenMRS
**Model used in Bahmni for maintain address hierarchy:**
address_hierarchy_address_to_entry_map                    
address_hierarchy_entry                                   
address_hierarchy_level
Whereas core OpenMRS maintain that through **location**.
Need to change in team management module so that it works with modified data model.

**Comment by maimoonak** [comment]
TM module  has been tested with Bahmni and it works fine. Bahmni also uses location for recording encounter / provider location. Please confirm this with Bahmni team. If required create a separate branch to apply these changes.

**Comment by sohelsarder** [comment]
I am not sure which bahmni version you have tested, also have you done with facility syncing? TM installed and run fine over bahmni but it lists facilities location not the provider hierarchal assigned location that require for login from openSRP app.

**Comment by maimoonak** [comment]
Ok. Maybe your case is different

**Comment by sohelsarder** [comment]
As per discussion with core bahmni team this could be manage differently from bahmniMRS provider management then linking with existing person.
