### ISSUE TITLE
Refactor and extend opensrp-schedule to be self-contained, extensible, independent module

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#12]
opensrp-scheduler doesnot do anything except creating few scheduler events (which are also in scattered across other modules) and providing functionality for Alert and Route. 
- Move ScheduleService and other scheduling related code (from opensrp-core) and everywhere here to make it completely independent. 
- Keep provision of access of this repository in other modules but core scheduling should be encapsulated here.
- Each module can create a schedule based on the custom criteria but those should use Services provided by this module. No scheduling logic elsewhere.

@mberg , @alihabib , @ndisha , @raihan-mpower , @julkarnain , @sohelsarder , @jayantchaudhari7 , @dimasciput , @raufdesu , @kercobo , @wahid-nwr

**Comment by maimoonak** [comment]
@kercobo All refactoring should be in a separate branch cloned from master as opensrp-server-schedule-iq. 
All other devs working on code are requested to NOT do any refactoring in core/schedule to avoid conflicts. Or atleast avoid making changes in scheduling part of core without coordinating with @kercobo .

**Comment by kercobo** [comment]
Sorry for the late respon, i've been working on another SID Project for the past few week.
i'll do it as fast as i can..

**Comment by maimoonak** [comment]
Hi @kercobo , I am working on this ticket.

**Comment by ndisha** [comment]
@maimoonak is it too early to also create a related issue on Rapidpro setup? For messaging? I can do that and ping Darius for help from his developers. Let me know!

**Comment by maimoonak** [comment]
Plz check the issue #14 and extend it or create a new one with this mentioned as Parent.

**Comment by maimoonak** [comment]
Closed as we are using different approach for this which described in detail in #48
