### ISSUE TITLE
Send SMS to FWV (field worker verifier) while in PNC form mother fever identified.

### ISSUE THREAD

**Issue by sohelsarder** [OpenSRP/opensrp-server#121]
Below is the requirement to send Temperature SMS-
**Alert ID**
FEVER
**Description**
Woman has fever on PNCRV-1/2/3
 **SMS Text :Banglish SMS Text: English**	
ALERT! (mohilar nam) proshober ak soptaher moddhe jor hoyeche. doya kore mohilar sathe jogajog korun je, tar jonokichu proyojon ache ki na.	
ALERT! (womanname) has a fever within a week of her delivery. Please communicate to see if anything is needed.	
 **Trigger**
If FWPNC1TEMP >=104 on PNCRV1 or

FWPNC2TEMP >=104 on PNCRV2 or

FWPNC3TEMP >=104 on PNCRV3 

on PNCRV1 / 2 / 3; As Form Received

**Whom**
FWV

**Comment by cagulas** [comment]
@sohelsarder Will you be using RapidPro to create this alert? Also, 104 degrees F is incredibly high. I think the recommendation is to alert a health worker if the woman reaches a temperature of 100.4 F or higher. @klzeller can you provide some input here?

**Comment by cagulas** [comment]
And is this for the mother or the child? The issue title specifies child, while the issue talks about the mother, or is it both?

**Comment by sohelsarder** [comment]
@cagulas: thanks for your valuable input, no we are not using rapidpro here, we are using local SMS carrier for it right now, we are going to use rapid pro for DGHS  vaccinator app notification delivery and  this is for mother only not child. thanks for correcting this.

**Comment by klzeller** [comment]
Yes, we should use 100.4.

**Comment by sohelsarder** [comment]
fever sms integration completed and tested at staging environment.
