### ISSUE TITLE
DHIS2 Opensrp Integration 

### ISSUE THREAD

**Issue by proshantokuet** [OpenSRP/opensrp-server#122]
We are going to follow the following steps.
1. DHIS2 setup(completed).
2. DHIS2 module study(OpenMRS-DHIS2 Integration Module, DHIS2 Reporting Module, DHIS Connector Module, DhisLocation Connector)(Working progress).
3. Configured openMRS for reporting data transmission.

**Comment by maimoonak** [comment]
We worked on a module which pulls locations from DHIS. Though dhis-integrator module on openmrs also pulls and allows mapping which is different from this module. 

https://github.com/OpenSRP/openmrs-module-dhislocation

**Comment by sohelsarder** [comment]
thanks @maimoonak, have you worked with openmrs dhis2 integration? are these above module addressed all or anything missing their as far you know. We really want to see our openSRP data to dhis2 would it be convenient to use these openmrs module and transfer data from openmrs to dhis2 or need to directly use dhis2 service for this.

**Comment by maimoonak** [comment]
Its difficult to suggest or recommend b/w the two..

The module needs refactoring and depending on dhis2 version needs serious refactorings. Maybe it would work well with older dhis2 versions. 

Though comparing to starting work from scratch its good to redesign it. There are some version issues b/w openmrs dependencies used, some inherent issues with architecture and compatibilty with dhis2 (like dhis allows null for code but module starts crashing if code is found null) and new ADX data exchange format was not working i.e. was not posting data.

Starting from scratch would not only take time and effort but it would also be very custom. Moreover, there is already alot of work done for this which should be reused.

Whether using existing module or starting from scratch a well planned, complete SDLC should be used that would also help other sites to adapt it.

**Comment by proshantokuet** [comment]
It seems  for  better understanding of openmMRS DHIS2 module needs to more explore basic functionalities of DHIS2, depth exploring DHIS2 user functionalities.

**Comment by maimoonak** [comment]
Not sure what approach BD team is going to adopt. But just to refer a discussion going on in OpenMRS community below is a link https://talk.openmrs.org/t/openmrs-dhis2-module/7502/21
