### ISSUE TITLE
 OpenSRP to DHIS2 connector for aggregated data transfer.

### ISSUE THREAD

**Issue by proshantokuet** [OpenSRP/opensrp-server#128]
We want to send various types of aggregated data to DHIS2.
Such as example
1. No. of ANC register in a day.
2. No. of Household in day.
4. No. of Woman in a day.
5. No. of child or new born (Male /Female)
6. GPS.
7. etc.
So that we can generate varous type report from DHIS2.

**Comment by cagulas** [comment]
How would the connector be set up? Would OpenSRP data go through SHR first and then go into DHIS2. What is the flow of data in this scenario?

Also, which OpenSRP deployment would this be for? Is this the FWA deployment with mCare or is this the separate OpenSRP deployment for DGHS with the HAs?

**Comment by sohelsarder** [comment]
@cagulas: No, earlier we planned that would be route through SHR, but got some case where SHR not in route and might not be in picture there data need to pass into DHIS2 directly from openSRP.

This is not we are planning for mCare as this is already in production there service disturbance in concern. This is we are planning for next deployment of OpenSRP in openSRP CRVS and  DGHS project.  After everything settle down there with DHIS2 we might consider to replicate that learning to mCare as well.

**Comment by cagulas** [comment]
So the flow would be directly from OpenSRP to DHIS2? Why not use the OpenMRS modules for DHIS2 that @maimoonak mentioned in another issue?
