### ISSUE TITLE
OpenSRP to DHIS2 connector for transfer details register data.

### ISSUE THREAD

**Issue by proshantokuet** [OpenSRP/opensrp-server#129]
We want to send/transfer register data to DHIS2.
Such as Example
1. Household Data.
2. Woman Data.
3. etc.
So that we can see a particular  details register data information from DHIS2.

**Comment by cagulas** [comment]
How is this issue different from https://github.com/OpenSRP/opensrp-server/issues/128 ??

**Comment by sohelsarder** [comment]
@cagulas : #128 is for aggregated data transfer where this is for details data transfer.

**Comment by cagulas** [comment]
by details, do you mean individual patient data? Are you looking to push this into Patient Tracker module?
