### ISSUE TITLE
Dghs server development and implementation for HHMemberReg registry

### ISSUE THREAD

**Issue by asifur77** [OpenSRP/opensrp-server#131]
We are going to work on the following steps:

1. Register and enroll new members in Household registry.
2. Add new members in Household registry.
3. Schedule BNF for eligible woman accordingly.

**Comment by cagulas** [comment]
BNF is birth notification form, no? Why are you scheduling BNF for eligible women in the HH register without first scheduling pregnancy surveillance form for them and registering their pregnancy?  Are there steps missing here?

**Comment by numeranazneen** [comment]
We will be collecting the pregnancy status information from HHRegistration Form, and if the woman is 'Pregnant' only then we are shifting her to Woman Register. I have checked PK Vaccination App, where they are scheduling TT vaccines for Pregnant Women only, so following the same logic we are moving only Pregnant Women to 'Woman Register' and scheduling BNF to get their outcome information.

**Comment by maimoonak** [comment]
@numeranazneen The app is not for pregnant women only. TT vaccine can be given to any woman of age 15-45 (of any marital status and of any pregnancy status) and app allows it. Its just the culture here that in live data you would not find any woman who is unmarried and not pregnant.

**Comment by cagulas** [comment]
@numeranazneen as Maimoona points out, all women can go in the Woman register, not just pregnant woman, and ideally, women start getting vaccinated against TT before their first pregnancy, so this is the preferable workflow as well (i.e., all women of 15-45 years of age get added to woman register to start getting vaccinated against TT). In the scenario you described, what happens when a woman becomes pregnant after she's already registered in the HH? Is there no form to transfer her to Woman register if she becomes pregnant after she's already registered in the HH?

Again, it's preferable for all women 15-45 to be added to TT woman register, but what is the actual practice or national guidelines in Bangladesh? Practically-speaking, when do women in Bangladesh receive their first dose of TT? Is it only after their first pregnancy?

@klzeller please provide some input here as well.

**Comment by numeranazneen** [comment]
@maimoonak  Ok got it. Thanks for the clarification. I checked our form and found the same logic that you have mentioned here, may be we updated the form correctly but didn't update the mockup. 

@cagulas did you check the mockup? I am not sure where should we add the PSRF form to collect the Pregnancy information. The page is already filled up with lots of information. :-/

We'll schedule the BNF for the Pregnant women, currently we are getting this information from the HHRegistration form only which Ashifur bhai was talking about, but once we'll add the PSRF we'll get same information from PSRF as well. So, this'll be an additional task.

**Comment by cagulas** [comment]
@numeranazneen let's discuss this workflow during the science pre-call today. I also don't understand why BNF is being recorded, if there's no other register for the woman to go in after she delivers her baby. As I understand it, there's only the HH, woman, child, and stock registers, so what happens to the woman's case after BNF is recorded?

No, I didn't see the mockups, where are they?

**Comment by numeranazneen** [comment]
I mentioned it in our last call that BNF is required to collect the information of the 'Outcome'. Whenever there'll be an outcome, we'll Register the newborn child in 'Child Register' and link the child with her mother. 

Similarly if the woman send Birth SMS, it'll immediately schedule BNF, which will be used to collect outcome data and register the newborn in Child register.

**Comment by maimoonak** [comment]
Sorry for typo. Though WHO recommended age is 15-45 and we dont have any upper limit specified in app but in training and field the upper limit followed is 49 years

**Comment by numeranazneen** [comment]
Ok. We'll make this change in the form. Thanks.

**Comment by numeranazneen** [comment]
@cagulas the mockups are in the SRS document that I shared with you in slack. and also uploaded in Google Drive (https://drive.google.com/drive/folders/0B42mFq702to6VFZhOEJ3dUc4VFk)

You already have access to this folder, where you can get all documents for DGHS.

**Comment by cagulas** [comment]
@numeranazneen that a separate folder and not within the Thrive Bangladesh folder. Can you move it to the Thrive Bangladesh folder? Sorry I keep asking you to share links with me, but please understand, each Thrive team has their own file management system in Google Drive, and it's become quite large, so it's hard for me to go searching for things on my own, and it's very much appreciated that you can share the links of these documents with me.

**Comment by numeranazneen** [comment]
We needed to give access to ThoughtWorks in these files/folders because we are working together, so I kept it outside the THRIVE Folder. Do you really want me to move that in THRIVE Bangladesh folder? Will that be fine if TW team get access to THRIVE folder?

**Comment by cagulas** [comment]
No, they shouldn't get access to entire Thrive folder, but as long as you add them to only the Bahmni folder and do not add them to the larger Thrive Consortium folder permissions, they won't have access. So, it's fine to do this.

**Comment by numeranazneen** [comment]
Ok.I moved that folder under THRIVE BANGLADESH. I gave them access only to 'OpenSRP-Bahmni-SHR Integration' folder
