### ISSUE TITLE
Uninque Health ID assignment from SHR/OpenHIE for openSRP register clients

### ISSUE THREAD

**Issue by sohelsarder** [OpenSRP/opensrp-server#187]

**Comment by raihan-mpower** [comment]
whenever a new household is added this is the state
![withhealthid](https://cloud.githubusercontent.com/assets/6203919/21502113/b7b475ba-cc77-11e6-942b-a3fdce4f527c.png)
after a new household is added the health id is synced from server and is added
![withhealthid](https://cloud.githubusercontent.com/assets/6203919/21502118/bdad0676-cc77-11e6-9599-c82cbc2d9e7d.png)
