### ISSUE TITLE
Create Facility Activity Report ETL Scripts

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#199]
This process will entail 3 steps:
- Creation of a facility report table for pushing data from openmrs tables into the etl table
- Creation of scripts to push data from the openmrs data tables into the report etl table
- Creation of a procedure for automating the syncing of the facility report table as new data is added

Once the facility activity report table is created and updated with the latest data, a report will be created on the openmrs reports module for exposing this data.

**Comment by mberg** [comment]
hi @geoffreymuchai Do we need to create a table for the facility?  Can't we just have a facility id be part of each client event that's recorded?

**Comment by geoffreymuchai** [comment]
@mberg We will not be creating a table for the facility. We will be creating an etl table that will pull in all the data required by the facility activity report into the same table so that the process of generating the report becomes quite simple and straight forward.

The reports on openmrs will be designed in a way where the facility id, location id and outreach area fields will be variables that can be used to filter the report data. We will also ensure that the data is a variable that can be changed depending on the report the user wants

**Comment by geoffreymuchai** [comment]
@mberg We will not be creating a table for the facility. We will be creating an etl table that will pull in all the data required by the facility activity report into the same table so that the process of generating the report becomes quite simple and straight forward.

**Comment by keymane** [comment]
Moved to https://github.com/OpenSRP/path-zambia-etl
