### ISSUE TITLE
Update address template for Zambia in OpenMRS

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#208]

**Comment by geoffreymuchai** [comment]
@cagulas is this issue something that i can work on tomorrow or beginning next week?

**Comment by cagulas** [comment]
As soon as you can, but let's say it should be complete by Monday, the 13th

**Comment by cagulas** [comment]
Got clarity from PATH. The address template will be:
Country
Province
District
Health Facility
Residential Area
Residential Address

**Comment by geoffreymuchai** [comment]
@cagulas I have applied the new address template but i am unable to test if the Zambia data displays it as we would expect.

**Comment by cagulas** [comment]
@gm Thanks, just logged in to look. The actual address data won't display until @jasonrogena adds the address OMRS mappings to the birth registration form.

In the meantime, I noticed that some of the address fields aren't displaying (i.e, Province, District):
![screen shot 2017-03-13 at 1 21 40 pm](https://cloud.githubusercontent.com/assets/3488986/23852401/42f8d7e8-07f0-11e7-8080-4c70bcc4f69b.png)

**Comment by jasonrogena** [comment]
@cagulas They should auto-update once @geoffreymuchai changes them on OpenMRS

**Comment by geoffreymuchai** [comment]
@jasonrogena What am i changing on the OpenMRS?

**Comment by jasonrogena** [comment]
@geoffreymuchai The address template

**Comment by geoffreymuchai** [comment]
@jasonrogena i have already updated that

**Comment by cagulas** [comment]
Closing this. New issue created where this will be addressed: https://github.com/OpenSRP/opensrp-server/issues/266
