### ISSUE TITLE
Team Management Module for OpenMRS-OpenSRP

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#21]
Component diagram and mockups as initial requirements are below. 
The module currently doesnot provide 
- RESTful API
- Team member selection/mapping on multiple locations
- Roles and privileges based on Teams

![teammanagement](https://cloud.githubusercontent.com/assets/4829880/6500589/6a2e99d6-c32f-11e4-9c5f-16397419ab4a.png)
![uimkupeditteam](https://cloud.githubusercontent.com/assets/4829880/6500590/6a3138a8-c32f-11e4-8b63-153b35f65ee1.png)
![uimkupteammembers](https://cloud.githubusercontent.com/assets/4829880/6500591/6a33dca2-c32f-11e4-956f-94a7cfd51520.png)
![uimkupteams](https://cloud.githubusercontent.com/assets/4829880/6500588/6a2c98de-c32f-11e4-82b6-e40f6bc600bc.png)

**Comment by MuhammadSafwan** [comment]
Restful API:
•	I haven't a faintest clue what REST is. Have to go through the documentation first and           understand the working of it.
•	Then have to see how to use it in the module.
Team Member mapping:
•	Have to first discuss it as to what exactly are the requirements, all the scenarios before changing so that no rework occurs.
Roles and privileges:
•	These too need to be discussed as what should be the roles and their privileges.
•	Who can assign roles etc. (sort of hierarchy) should be made before as to reduce the rework as much as possible.

Not sure about the timelines for now but will soon come up with some estimates.

**Comment by alihabib** [comment]
Hi Safwan,

Please check with Owais about REST and OpenMRS.  He has previously worked
on REST tickets and should be able to guide you through it.

Ali

-- typed on my mobile. Please excuse typos and brevity

**Comment by MuhammadSafwan** [comment]
Yup. I was thinking the same. I thought to ask him today but as he's busy for the call, I have thought of asking tomorrow.

**Comment by ndisha** [comment]
@maimoonak @MuhammadSafwan thanks a mill for this functionality.
 Before I close this out, I wanted to flag out this point: Roles and privileges based on Teams; are we going to work on this?

**Comment by maimoonak** [comment]
I think this functionality is not a priority rightnow. We can create another issue if needed for V2. @MuhammadSafwan has put a great effort in making this work, especially the multiple locations thing on a very short notice.
@MuhammadSafwan , when you are finished with priority work that you are working rightnow, please close this ticket with technical description of the features available, changes done to initial model, and the functionality that is not one like "Roles and privileges based on Teams".

**Comment by maimoonak** [comment]
- Team management module has been done and uploaded on server. The code is shared on [openmrs-module-team](https://github.com/OpenSRP/openmrs-module-team).
- All of the functionality is implemented in addition to one-to-one mapping b/w team&location and one-to-many mapping b/w team-member&location.
- All REST services exists to provide access to team and team member data
- The hierarchies are NOT displayed though
- The role and permission for teams is not part of this release.

**Comment by maimoonak** [comment]
The updated diagram for Team Module. Note that this is just to describe (and not a standard component diagram) the architecture of module and connectivity b/w different components. 
![teammodule](https://cloud.githubusercontent.com/assets/4829880/8927330/0ed17cc0-3530-11e5-932d-a50d0d96d936.png)
