### ISSUE TITLE
Unresolved Motech dependencies?

### ISSUE THREAD

**Issue by plmercereau** [OpenSRP/opensrp-server#210]
Hello,
When I follow the steps of the wiki to build the OpenMRS WAR file from a clone from the GitHub repository, I am stuck with an error that seems to be linked with the unavailability of a motech service.
In the log of maven:

[ERROR] Failed to execute goal on project opensrp-common: Could not resolve dependencies for project org.opensrp:opensrp-common:jar:0.1-SNAPSHOT: Failed to collect dependencies at org.motechproject:motech-platform-common-api:jar:0.11: Failed to read artifact descriptor for org.motechproject:motech-platform-common-api:jar:0.11: Could not transfer artifact org.motechproject:motech-platform-common-api:pom:0.11 from/to motech.opensrp (http://nexus.motechproject.org/content/repositories/opensrp-server): Failed to transfer file: http://nexus.motechproject.org/content/repositories/opensrp-server/org/motechproject/motech-platform-common-api/0.11/motech-platform-common-api-0.11.pom. Return code is: 503 , ReasonPhrase:Service Temporarily Unavailable. -> [Help 1]

Any idea on this?
Many thanks in advance!

**Comment by craigappl** [comment]
The nexus repo is down. I emailed Pawel at SolDevelo and Sheel at Dimagi to see if they can reboot the box.

**Comment by mberg** [comment]
We have a docker instance also to help faciliate the install

**Comment by plmercereau** [comment]
Thanks for your prompt reply. Actually I tried the docker option, but as I need a compiled WAR file, I am stuck at the same stage. If any docker instance with the webapp already installed is available, I'll be glad to get it.
Thanks

**Comment by craigappl** [comment]
Sheel rebooted the server and it seems like it's up. Can you try building again?

**Comment by plmercereau** [comment]
Many thanks for your prompt support! The server is up and running, but I am struggling now to pass the tests of the maven build - most likely due to my rusty java skills, so not related to the initial issue, that could be closed I suppose.
A built WAR file would be of some help so I can finish the dockerization though.
Thanks again, Matt and Craig!

**Comment by mberg** [comment]
Hi @plmercereau really glad you got it working.  Just curious of who you
are and your interest in OpenSRP?  Great to have more people checking it
out!
