### ISSUE TITLE
Push HIA2 report to DHIS2 from OpenSRP Server

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#211]
Using the data from the form submission for HIA2 (https://github.com/OpenSRP/opensrp-client/issues/438), create the full HIA2 report in Ona's DHIS2 instance.

**Implementation Details**
- [x] Format HIA2 form submission from the android client into the DHIS2 format below
The data should assume the following format:
```
{
  "dataValues": [
       { "dataElement": "WFxN7txijYV", "period": "201401", "orgUnit": "qGmkMMWDHOm", "value": "12" }  
       { "dataElement": "EtOcAIMlPG9", "period": "201401", "orgUnit": "PijOYGG1b54", "value": "14" }
   ]
}

  NB:
  Org units need to be converted from OpenMRS uuids to DHIS2 orgUnit Ids.
```

- [x] Automatically sync reports to DHIS2
Calculated indicators should not be pushed to DHIS2 e.g. `CHN2-061` whose value is derived from `[CHN-055] + [CHN-060]`

**Comment by tobiasmakai** [comment]
Noted

**Comment by geoffreymuchai** [comment]
The structure of the reports that will be stored in couchdb is:

```
{
  "dateCreated": "2017-05-22T15:12:28.894+03:00",
  "locationId": "826684c3-6d82-4b0b-a750-a5f7f98b8608",
  "reportType": "HIA2",
  "formSubmissionId": "5f52c82f-ea29-469e-96d6-f95a6cc8fbe9",
  "providerId": "biddemo",
  "duration": 0,
  "indicators": [
     {
         "name": "CHN2-065",
         "dhis2_id": "DSbbltBORY3",
         "value": 20
     },
     {...}
  ]
}
```

**Comment by geoffreymuchai** [comment]
@maina The reports will need to have a `reportDate` key similar to the event date in the event documents

**Comment by cagulas** [comment]
This is done. Syncing to test DHIS2 Ona server. We'll sync to production once we have the final set of data elements defined from Zambia's DHIS2.
