### ISSUE TITLE
Create On-time Vaccination Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#224]
**Description**
This indicator is a measure of timelines in the delivering the correct vaccine at the correct time to each and every child that was in need of a vaccination. The calculation accounts for all antigens and all children within the facility’s catchment area.

The acceptable period of providing a vaccination is not limited to the specific date the vaccination is due, but rather a provision window that equates to 10 days. This means that the child is considered on-time if he/she receives a given vaccine up to 10 days after they are scheduled to be due that vaccine. The provision window is defined as the difference between the earliest acceptable delivery date/time and the latest acceptable delivery date/time.

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
