### ISSUE TITLE
Create Vaccine Wastage Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#225]
**Description**
Month to month visualisation of the number of vaccine doses that are issued to a health facility but that are not administered to children. 

Doses issued would be a physical count of the doses removed from stock. 
Doses administered would be generated by the system from the number of children who are recorded as having received a vaccine in that period

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
