### ISSUE TITLE
Create Stock Out Days Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#226]
**Description**
Month to month visualisation of number of days the facility could not administer vaccines because the vaccine was out of stock

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
