### ISSUE TITLE
Create Number of births Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#231]
**Description**
Month to month visual of number of births recorded as having occured at that facility in that month

**Report Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
