### ISSUE TITLE
Create Rate of fully immunised children Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#232]
**Description**
Month to month visual number of children < one year who have received the complete BCG, OPV series, DPT-Hib+Hep1 series, PCV series , RV series and measles/MR 1 within 10 days of each antigen being due as a proportion of the facility's <1 target population

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
