### ISSUE TITLE
Create Day with no stock out Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#233]
**Description**
Number of days the facility has been stocks with all atigens

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
