### ISSUE TITLE
Create Annual Coverage - WHO Standard Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#235]
**Description**
Annual visual of the percentage of fully-immunized children (For particular vaccine) > one year compared to the total number of surviving children > one year in the target population.

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
