### ISSUE TITLE
Create Attendance child health total Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#236]
**Description**
Month to month visual of the total number of children < 5 who attended clinic that month

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
