### ISSUE TITLE
Create Stock Balance Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#238]
**Description**
On demand visual of the balance of stock in doses and vials relative to the minimum/reorder level for that antigen

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
