### ISSUE TITLE
Create Stock Usage Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#239]
**Description**
On demand visual of the amount of stock used within a specified date period for each antigen

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
