### ISSUE TITLE
Create Stock Projection Report

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#240]
**Description**
The amount of stock on hand juxtapose the amount of stock that will be required to immunise the number of expected children for that period

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Comment by cagulas** [comment]
Closing for now. Priority indicators are being finalized and new issues will be created for them.
