### ISSUE TITLE
Unique Code Import CSV from OpenMRS to InteractiveHealthSolutions/qridgenerator

### ISSUE THREAD

**Issue by jasonrogena** [OpenSRP/opensrp-server#245]
Add support for importing unique codes from OpenMRS into https://github.com/InteractiveHealthSolutions/qridgenerator for up to 300,000 codes

**Comment by cagulas** [comment]
Initial batch will be 300K codes. More batches will need to be printed later, as the need arises.

**Comment by cagulas** [comment]
Some context on this: IDs generated in OMRS will either go to the tablet in batches to be used in the birth registration forms, or they will be imported into the QR code tool to be printed as QR code stickers. On the tablet, when registering a new kid, the form will pre-load an ID from the batch of IDs on the device. If no, QR code is scanned in the form to override the pre-loaded ID, then the pre-loaded ID is submitted and saved as the child's ZEIR ID. If the user scans a QR code in the form, the ID from the QR code should override the pre-loaded ID. When saving the form, the ID from the QR code will be saved as the child's ZEIR ID and the pre-loaded ID should be returned to the un-used batch of IDs on the device, so it can be loaded into another form.

**Comment by cagulas** [comment]
The size of the QR codes will be the "5-column" size. Let's hold off before exporting the pdfs until we get the final go-ahead from the printer.

**Comment by cagulas** [comment]
After speaking with team, let's send an initial batch size of 100-page pdf file to the printer to see if the printer is capable of handling it.

**Comment by geoffreymuchai** [comment]
@maina since this functionality was tested and found to be working as expected, I am closing the issue

**Comment by geoffreymuchai** [comment]
@maina I have tested this on production and it does not work nor does it raise an exception that i can see in the logs

**Comment by geoffreymuchai** [comment]
@maina I have tested this on production and it does not work nor does it raise an exception that i can see in the logs

**Comment by geoffreymuchai** [comment]
@maina @jasonrogena  closing this given that it successfully works in production
