### ISSUE TITLE
Fix remaining issues with back data import

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#247]
*High Priority*
- [x] BCG date recorded issue (already noted by Geoffrey)
- [x] Are the next vaccines syncing? My data is off on my tablet, so can't test for sure, but see sample child. If his 6 week vaccines were given on March 20, 2017, then the 10 weeks should be showing as currently due as from April 17th, 2017.

*Medium Priority*
- [x] Home health facility field not being populated for any child it seems
- [x] Child's DOB and Date First Seen are in different date formats on the detailed view (dates are correct though, but looks confusing)
- [x] Place of birth (home or health facility) seems to be incorrect. According to the back data in Ona, the sample child was born at a health facility, but in the app it is showing "Home" in the detailed view. This must be a mistake, because the birth health facility was selected, which wouldn't have been possible if home was selected.

**Comment by cagulas** [comment]
Priority is to make sure next vaccines are syncing for the roll-out next week.

**Comment by geoffreymuchai** [comment]
@cagulas All the issues have been QA'd and confirmed to be working
