### ISSUE TITLE
Large Number of Birth Registration Events on CouchDB

### ISSUE THREAD

**Issue by jasonrogena** [OpenSRP/opensrp-server#257]
There seems to be an extraordinarily large number of birth registration events owned by the 'biddemo' user on Zambia's CouchDB instance:

Use this CouchDB map function to extract the records:

```
function(doc) { if(doc.type == 'Event' && doc.eventType=='Birth Registration' && doc.providerId== 'biddemo') {emit(null, doc._id)} }
```

**Comment by cagulas** [comment]
Closing, no longer relevant.
