### ISSUE TITLE
sync_record MySQL Table Size

### ISSUE THREAD

**Issue by jasonrogena** [OpenSRP/opensrp-server#258]
The `sync_record` MySQL table seems to be larger than expected (36GB as of May 17th 2017) in Zambia's OpenMRS instance.

**Comment by maina** [comment]
This seems like it's an issue to do with openmrs sync module
https://wiki.openmrs.org/display/docs/Sync+Module
Since currently we don't have server - server sync we can uninstall the module

**Comment by jasonrogena** [comment]
Disabled the sync module using the instructions on it's wiki page
