### ISSUE TITLE
Important API modeling concern : Individual --> Client

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#26]
Parent : #9 

@mberg @djazayeri 
I remember the discussion we had on Thursday of Thrive Meeting (Day 4th). We had decided to choose name Client instead of Person since in future we were hoping to have Other types of things as our Clients. 

But trying modelling the entities I encountered a duplication. We have Client which is a Person with different attributes, and also we a User and Provider (or could be any other entity) who also have similar type of  fields. 

What I tried doing is introduced an abstract class Individual [could be person, animal, tree etc whatever we need to capture data for]. Our Users, Providers, Clients etc would inherit this class along with specific fields as per requirements. Our FormSubmissions would be linked to an Individual class [could have data for Client, Person etc]. It would provide us provision to fill form for Any entity in our system. A cow, tree, Client, a user registration, a provider registration etc etc... whatever we want to fill....

Does this approach seems fine to you ? Since this is our core and base api so your feedback is very important.

@alihabib , @ndisha , @raihan-mpower , @julkarnain , @sohelsarder , @jayantchaudhari7 , @gigix , @cagulas , @dimasciput , @raufdesu , @kercobo , @wahid-nwr , @MuhammadSafwan

**Comment by alihabib** [comment]
I think the approach probably makes sense but the name Individual could be misleading (still seems to indicate a Person). I'm at a loss for what might be a better name however. Some options that come to mind (but are admittedly not brilliant) are FormTarget, FormEntity, RegisterTarget, RegisterEntity.

Ali

**Comment by sohelsarder** [comment]
I think Ali cover most what left? what about 'creature' ? that could be a person or a cow or a tree or any living object

**Comment by wahid-nwr** [comment]
I think what we are talking about an object which has a common feature in our project that is "an object which gets visited by any of the users". so the name should describe that aspect

**Comment by mberg** [comment]
Just to clarify is there a conflict with using the word Client? 

Client would be preferable and I think follows the OpenMRS approach with Provider.

**Comment by alihabib** [comment]
Nope no conflict as such. It's a semantic thing. If we are referring to
things other than people as mentioned in the post (is there a use case for
that?), then the word Client might not be intuitive. If it's an edge case
then no point worrying about semantics...Client will work.

Ali Habib
Chief Executive Officer
Interactive Health Solutions
Ph: +92-21-34327697
ali.habib@irdresearch.org
http://www.irdresearch.org

**Comment by maimoonak** [comment]
There is no issue in using Client. The base entities are Client, Provider, User, Location. But all three Client, Provider, User have many attributes in common. Also these all are eligible for a form to be filled for. E.g. Client [all forms in registers], Provider [registration, termination, transfer, etc etc], User[registration, suspend, etc]. So we wanted a base entity that can describe generic attributes for all of these [in OpenMRS it is Person but our Client can be a non-human too]. Attached Diagram shows Class diagram for Basic classes from API. Classes without pkg name are base domain objects.
This may help in getting big picture of API. The methods[except important ones] are hidden for domain object but for service provider classes.
![apicldg](https://cloud.githubusercontent.com/assets/4829880/6652756/848b6d90-ca9b-11e4-8e54-6b8bfd8d48af.png)

**Comment by wahid-nwr** [comment]
if we have to create an object like a household or a family or an animal, in those scenarios attributes of BaseEntity will not be sufficient. I dont understand how we are going to use the map of identifiers in Client object. If we are thinking BaseEntity as a person then what is the use of Client (there is a attribute baseentity in client).

**Comment by wahid-nwr** [comment]
if client is a object that can refer to human/non-human objects then why not we call client a BaseEntity and current BaseEntity a Client.

**Comment by maimoonak** [comment]
Household and Family is a collection so it needs a completely different mechanism to record the data with reference to collection of Clients.
Animal; if is registered in system as Primary object to be taken care of then it could be referred as Client.
The identifiers is a Map to collect other unique non-opensrp identifiers like CNIC, Passport#, RashanCard #, Driving license#, etc (it is totally customizable by Client system) .
BaseEntity is just a base class to generalize min data for each type of entity in system like User, Provider, Client etc. Each entity refers a base entity so that it can be used by FormSubmission or to link different roles in system. 
Client is our Primary object for whom our system is design to take care of. User, Provider are not our Clients thats why we can not switch Client and BaseEntity.

**Comment by wahid-nwr** [comment]
thanks for clarifying maimoona. But the reason I was talking about this that we have to introduce a non human object (household) in mCare2. So if we introduce a Household as a collection of clients then we have introduce a new object for implementing objects which are non-human in the core.That's becuse the non-human object also have some basic information like when created, who created and where is the location of that. Please clarify I am understanding wrong.

**Comment by maimoonak** [comment]
Resolved and Individual is named as BaseEntity
