### ISSUE TITLE
New register module

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#27]
Refactor opensrp-core and make a new module as opensrp-register. The module should be independent and should contain register specific code that currently exists in opensrp-core. Also the register module should provide a contract/interface for the min a register should have!
@julkarnain could you give it a thought and share with us the basic design and architecture. It could be changed along the way depending on needs..

**Comment by julkarnain** [comment]
Concept regarding opensrp-core and opensrp-register
opensrp-core: This module should be an independent, extensible and loosely coupled. There have only the common and core classes, common domain and repository, common schedule services, reminder, interfaces to handle registers. The interfaces would be extensible from any other custom module and  it may have client specific registers.  Any project for any country or org  it could be added as dependency project and could extend the interface  and apply the services as per requirements

opensrp-register:  This module should be implemented and extended module of the core. Here, would be the project/client/org specific registers,domain, services, schedules. Everything would be customizable without worried about the core.

**Comment by maimoonak** [comment]
Merged with master. @julkarnain if possible please write down some technical description here..
