### ISSUE TITLE
Vitamin A, Deworming, and ITN encounters not appearing in OMRS

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#284]
See dummy records submitted below. None of these is appearing in OMRS, and it's been 24 hours, and the tablet has synced successfully.

- Vita A IFC 2 on 4 July 2017 (Hugo Weaver, ZEIR: 5370200)
- Vita A 1 on 12 December 2016 (Natalie Phiri, ZEIR: 1405992)
- Deworming 1 on 12 June 2017 (Natalie Phiri, ZEIR: 1405992)
- ITN 1 (net provided date: 4 July 2017) (Hugo Weaver, ZEIR: 5370200)
- ITN 1 (net not provided, but sleeping under net) on 5 July 2017 (Natalie Phiri, ZEIR: 1405992)

**Comment by faith-mutua** [comment]
Issue fixed
