### ISSUE TITLE
Auto downloading of form_definition.json

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#29]
Parent #17 
The folder form in opensrp-core contains form_definition.json of all forms on client side. We may want to make it auto synchronizable with form_definition.json. Is it possible to do so? 
@raufdesu Could you please dig into the code and write down step-by-step guide of how it is accessed from client, processed in core and then how does it link it with MCTS reports and send data back to client for reports generated! What impact would it make if we try auto downloading of form_definition.json from client. How flexible its should be?

The other approach we wanted to work on was to download forms from server on client. but it was not possible since it needed  complete change of architecture and was not possible for current release. Trying exploring it you may want to compare both approaches too.

**Comment by sohelsarder** [comment]
We should not totally rule out the possiblity of downloading form from openSRPserver, we need to find out total dependency and changes requirements for both server and client side for it. If we could not adopt this features then we will loose the basic flexiblities of changes in form in middle of project launching which is very common for various projects. @raihan-mpower : could you please add your client requirements here if we want to do it anyway?

**Comment by raufdesu** [comment]
@maimoonak one quick question here, so we want to make form_definition.json on the client side to be able to auto synchronize with form_definition.json on the server side, right?

i'll try what i can do

**Comment by maimoonak** [comment]
There is a folder in core that has form definitions for all forms on client. The idea was to prevent developer from copying and pasting files on both sides. Most of the times if there are minor changes on client side developer may not feel the need to replace the server side version. specifically if it is in production a minor change on client side should not require redeployment on server side. But the implications and how client would handle this, @raihan-mpower need to provide his feedback.

**Comment by raihan-mpower** [comment]
well one way of doing it is syncing the forms from the server. As in make changes in forms in the server side and then sync the changes and form versions on the client side.....that way we can have uniform form versions on both sides.

**Comment by raufdesu** [comment]
just to make sure, another question.
on the server side, there is only form_definiton.json on the form folder,
right? while on the client side the form folder not only contain
form_definition.json but also form.xml and model.xml. if we want to make
some change into form_definiton.json doesn't that mean we need to make some
change into the form.xml and model.xml also? is it right or did i miss some
point here? this could become a problem if we want to make the client
autodownloading the form from the server.

i've also run some testing on the server side last week. when the server
(opensrp_web) still running and i try to modify, even delete the
form_definiton.json that located
in: opensrp-server\opensrp-web\target\classes\form\
or: opensrp-server\opensrp-web\target\opensrp-web\WEB-INF\classes\form\
even the one inside opensrp-web.war and try to upload the data from the
client side, it's not really affecting anything. my conclusion is, we need
to recompile and re-run the server after we make any change into the
form_definiton.json.
i still need to do more testing for this, to make sure.

On Thu, Mar 12, 2015 at 7:49 PM, raihan-mpower <notifications@github.com>
wrote:

> well one way of doing it is syncing the forms from the server. As in make
> changes in forms in the server side and then sync the changes and form
> versions on the client side.....that way we can have uniform form versions
> on both sides.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSRP/opensrp-server/issues/29#issuecomment-78465772>
> .
>



-- 
regards,


Ra'uf

**Comment by maimoonak** [comment]
Thanks @raufdesu for raising some of the important concerns. 

Today we discussed the issue with other changes required for the sprint in detail. @raihan-mpower provided his comments on #3 and it appears that we have to do the openmrs mappings on server side rather than on client side as opposed to our initial plan. The idea seems more sensible and doable since none of us has expertise in enketo and ziggy. Also making these mappings on server side would make code more readable and manageable. 
That was just a background of why we are going with the suggested approach. 

Now provided that we have mappings on server side , it brings the issue at top in the priority list (earlier it was at the bottom).
So now as per our plan, we are going with the following steps.

#### On server side
- Make all files of forms available in folder i.e form_definition.json, model.xml, form.xml
- The files would be pulled by client if there is any change in form_data_definition_version
- @raihan-mpower is looking into possibility of moving the forms to sdcard from assets folder to allow hot-swapping of the files.
- This needs to be facilitated by web services [http requests by client to server]
  - Service that provides the latest form_data_definition_version for given form_id/name
  - Service that provides the list of latest form_data_definition_version for ALL forms
  - Service that provides the actual files (3 files, in zip format probably) as a result of request for specified form_id/name

#### On client side it needs to provide
  - Compare the existing form_data_definition_version versions and update the files if current version on client is lesser than server version
  - If client version is outdated, download latest files from server for the given form_id/name and unzip the zip file and put the files in respective folder onsdcard
  - Move form folder from assets to sdcard  (based on Kiran`s input) 
  - Make sure to submit all pending formSubmissions first incase form_data_definition_version has been updated on server side.

The issue of form not getting updated might be because of web server cache. We can look into the issue in detail but stopping and starting server again (sometime cleaning tomcat work directory) usually solves the problem without any real compilation or app build. 

Also, the form folder in server is located inside opensrp-core (in opensrp-register for latest commit). For now we would updating it directly on server but in longer run we would provide an interface to update it via user interaction and this would lead to make it move to webapp folder in opensrp-web instead of resources folder.

**Comment by dimasciput** [comment]
I will use following json format for the server response in **Service that provides the list of latest form_data_definition_version for ALL forms** :

```javascript
{
	success : true,
	formVersions : [
		{
			"formName" : "ec",
			"formDataDefinitionVersion" : "1"
		},
		{
			"formName" : "anc",
			"formDataDefinitionVersion" : "2"
		}
	]
}
```

**Comment by sohelsarder** [comment]
Hi Everyone,
Finally, I came to ready with require services and coding staff of form auto downloading. Here the following service opensrp client will get from openSRP server,

Get All Current Available Version of form at server:
Request URL: http://{host}:{port}/getAllAvilableVersion 
Response:{success : true, formVersions : [{formName: PNC_Registration, formDataDefinitionVersion: 2},{formName: ANC_Registration, formDataDefinitionVersion: 1}]}

Download form with particular form name:
Request URL: http://{host}:{port}/getForm?formname=PNC_Registration
Resonse: Binary of zip file for requested form (model.xml,form_definition.json, form.xml)

Here is the simple code for FormDownloadController, that you @maimoonak might put into openSRP server,
package com.mPower;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

import javax.ws.rs.GET;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.ResponseBuilder;
import javax.xml.ws.WebServiceException;

import org.codehaus.jackson.JsonFactory;
import org.codehaus.jackson.JsonParseException;
import org.codehaus.jackson.JsonParser;
import org.codehaus.jackson.JsonToken;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;


@Controller
@RestController
public class FormDownLoadController {
	
    private static final String FORMS_DIR = "Path to your Forms/Forms/"; //Path to Forms directory
    private static final String FORMS_DEFINITION_FILE_NAME = "form_definition.json";
    private static final String DS = "/"; 
  
    @RequestMapping("/getAllAvilableVersion")
    @Produces("application/json")
    public @ResponseBody String getAllAvilableVersion() {
    	return readFormDifinitionFromDirectories();
    } 
    
	/*
	 * Service method transfer file as
	 * a attachment
	 * */
	@GET
	@RequestMapping("/getFile")
	@Produces("application/zip")
      public Response getFile(@RequestParam(value="formname", defaultValue="form_submission_samples") String formname) {
		 String filePath =  FORMS_DIR + formname + "//" + formname + ".zip";
		File file = new File(filePath);         
        ResponseBuilder response = Response.ok((Object) file);
        response.header("Content-Disposition", "attachment; filename=\""+ formname + ".zip" + "\""); 
        response.header("Content-Type","application/force-download");
        response.header("Content-Transfer-Encoding","binary");
        response.header("Content-Length",file.length());
        return response.build();
    }
	
	/*
	 * Service method transfer file as
	 * a byte stream
	 * */
	@GET
	@RequestMapping("/getForm")
	@Produces("application/zip")
    public static byte[] getForm(@RequestParam(value="formname", defaultValue="form_submission_samples") String formname) {
        String filePath =  FORMS_DIR + formname + "//" + formname + ".zip";   
        try {
            File file = new File(filePath);
            FileInputStream fis = new FileInputStream(file);
            BufferedInputStream inputStream = new BufferedInputStream(fis);
            byte[] fileBytes = new byte[(int) file.length()];
            inputStream.read(fileBytes);
            inputStream.close();             
            return fileBytes;
        } catch (IOException ex) {
            System.err.println(ex);
            throw new WebServiceException(ex);
        }      
    }
	/*
	 * Utility method read Forms directories 
	 * recursively find name of available forms 
	 * and their respective versions and then 
	 * return as a json string
	 * */
	private static String  readFormDifinitionFromDirectories(){
		String formName_Version_DefinitionJson = "{success : true, formVersions : [";
		String formVersionDefinition = "";
		File file = new File(FORMS_DIR);
		File[] files = file.listFiles();
		for (int i = 0; i < files.length; i++) {
			formVersionDefinition = getFormName_Definition(files[i]+ DS + FORMS_DEFINITION_FILE_NAME);
			if (files.length > 0 && i< files.length-1){
				formName_Version_DefinitionJson +=	formVersionDefinition + ",";
			}else{
				formName_Version_DefinitionJson +=	formVersionDefinition;
			}		
		}
		formName_Version_DefinitionJson += "]}";
		return formName_Version_DefinitionJson;
	}
	/*
	 * Utility method read form definition json
	 * find its name and version 
	 * and return it as a json string
	 * */
	private static String getFormName_Definition(String filePath) {
		String formName = "";
		String versionNo = "-1";
		String fieldname = "";
		JsonFactory jfactory = new JsonFactory();		
		JsonParser jParser;
		try {
			jParser = jfactory.createJsonParser(new File(filePath));
			while (jParser.nextToken() != JsonToken.END_OBJECT) {

				fieldname = jParser.getCurrentName();
				if ("form_data_definition_version".equals(fieldname)) {
					jParser.nextToken();
					versionNo = jParser.getText();
				}
				if ("form".equals(fieldname)) {
					while (jParser.nextToken() != JsonToken.FIELD_NAME) {
						jParser.nextToken();
						fieldname = jParser.getCurrentName();
						if ("default_bind_path".equals(fieldname)) {
							jParser.nextToken();
							formName = jParser.getText().substring(16,
									jParser.getText().length() - 1);
						}
					}

				}
			}
			jParser.close();
		} catch (JsonParseException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return "{formName: " + formName + ", formDataDefinitionVersion: "
				+ versionNo + "}";
	}
}

**Comment by maimoonak** [comment]
DONE with following changes:
1 - Json also contains another variable 'formDirName' for each form. This is because formDirName is one which contains form files. This should be sent as param with request for form download.
```
    {"formVersions" : [{"formName": "ANC_Close_EngKan", "formDirName": "anc_close", "formDataDefinitionVersion": "2"},
    .......,
    {"formName": "Child_Vitamin_A_EngKan", "formDirName": "vitamin_a", "formDataDefinitionVersion": "1"}]}
```
2 - The Controller doesnot assume that a zip file would already be present, rather it creates a zip file on the fly with file names property "form.download.files" specified in opensrp.properties
3 - All code now uses Spring Controller and response instead of rest API

The documentation for Client system is present here https://smartregister.atlassian.net/wiki/display/Documentation/Form+Autodownload+for+Client
