### ISSUE TITLE
Investigate syncing issues

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#298]
- [ ] Occasionally, the app shows "sync complete" status before all children are synced to the tablet. If you hit the sync button again, more kids will sync.

Please add to this issue if people notice anything else.

**Comment by ndegwamartin** [comment]
We can show an message specific to the particular sync batch in the toast notification 
e.g. Batch 1/10....Batch 2/10 ....Batch 10/10 Sync Complete

**Comment by cagulas** [comment]
The app is now showing sync failed when all of the kids fail to sync. We'll leave this issue open so that we can implement the batch syncing when we switch to postgres.

**Comment by cagulas** [comment]
Closing, out of date.
