### ISSUE TITLE
Data model to be defined using medical concept dictionary

### ISSUE THREAD

**Issue by mberg** [OpenSRP/opensrp-server#30]
This is addressed by #9 ?

@maimoonak can you please confirm?

**Comment by maimoonak** [comment]
If we are going with FormSubmission the concepts would be inside each FromField, and if go with Event it would be mapped with concepts too. "medical concept dictionary"- does this mean anything else other than openmrs concept dictionary? Do you mean it mappable with ANY standard dictionary?
@mberg

**Comment by maimoonak** [comment]
Resolved and Now Couch has Event and Obs which contains data, concept mapping and link back to actual form submission
