### ISSUE TITLE
Encounter does not appear in OMRS after first name warning

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#309]
MT: there was a warning about the first name and i think when that happens it may miss to create the encounter for the visit 

Dummy child `Bota` (no first name) with ZEIR ID: `4714812` initially failed to be created in OMRS, and when the record did appear in OMRS, the birth registration encounter form failed to appear in the Visits tab. It might have something to do with the no first name (which is allowed in ZEIR).

This is on test apk with cagulas login.

**Comment by manutarus** [comment]
Added checks to put a place holder incase of an empty string for first name
