### ISSUE TITLE
Investigate why patient isn't being created in OMRS after sync to couch

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#315]
This is reported in both test and production servers (could be same or different issue in test vs. production, not sure). In test server, cagulas user created dummy patient `Lillian Potter` with ZEIR ID: 4979324.

In couch, it's showing the OpenMRS UUID is `null` for some reason.

http://46.101.51.199:5984/_utils/document.html?opensrp/10e9e211efadb369551651c4022a7616

For the patient created in production server, I noted that the OpenMRS UUID field is missing from the client json.

**Comment by cagulas** [comment]
Three additional dummy records to investigate on test server (registered by user faith):

`Jilani Wane` `4536789`
`Leah Neema` `7568902`
`Turry Kim` `3425671`

For the above 3, I have noted that OpenMRS UUID field in client json is either `null` or missing.

**Comment by faith-mutua** [comment]
Issue fixed

**Comment by cagulas** [comment]
@manutarus What was the issue here as to why these records weren't getting created?
