### ISSUE TITLE
Handling inputs other than form submissions e.g. mjivita submission, birth sms notifications (through rapidpro)

### ISSUE THREAD

**Issue by ndisha** [OpenSRP/opensrp-server#32]
This is currently not supported therefore it needs to be considered while working on:

Parent Issue #3 

@maimoonak @raihan-mpower @sohelsarder

**Comment by maimoonak** [comment]
During the sprint it was decided that mjivita app would send FormSubmission as required by OpenSRP. @sohelsarder has been coordinating within his mcare team on this.

**Comment by ndisha** [comment]
@sohelsarder from our call yesterday, you mentioned that some of this has been done, could you document that here.

**Comment by sohelsarder** [comment]
openSRPSubmissionAdapter is going to build inside mjivita+ application. Currently all form for jivita application is XForm and data collected as a XML. For this adapter to work all mijvita+ form need to translate into XLSForm then  to create model.xml, form_definition.json from it finally this adapter will create formsubmission.json from jivita's current xml data. We don't  get jivita's translated form yet but with a sample xlsform we started building of jivita+ data translation adapter. Presumably it will ready by end of the next week then it will ready to post some sample json payload to openSRP server. 

@maimoonak / @julkarnain : Will you give me the rest service URL for openSRP server submission handler where we could able to post some json payload?

**Comment by maimoonak** [comment]
@sohelsarder The server make client app crash if it has any inconsistent/invalid form submission. Could you plz build a war file from master branch and deploy it on your localhost. 

@raihan-mpower @ndisha what do you suggest? @raihan-mpower id my assumption correct that submissions from @sohelsarder may cause your app crash?

**Comment by sohelsarder** [comment]
@maimoonak : I totally agree with you and i could check with local openSRP instances but it would be vulnerability issue for openSRP application if one client submission can crush the other client. It indeed require self protection (validity/data inconsistency checking inside openSRP server application) so that application never goes into inconsistent state.  So any minimal required submission attribute missing from any client will experience submission failure and will receive error message accordingly.

**Comment by ndisha** [comment]
@maimoonak @raihan-mpower @dimasciput; I agree with @sohelsarder, we need to work on the stability of OpenSRP - do we need to create some tests around each functionality?

**Comment by sohelsarder** [comment]
@maimoonak @raihan-mpower @dimasciput @ndisha @julkarnain
As currently application  in a stage of well dealing with native client (openSRPClient) submissions in its revise architecture and definitely great applause for the team for all of your hard works.

 Now we can check with how it performs with non native client (mjivita+) submissions. We have to check whether openSRP server and Client deals with dual version of data for same clients (women) in a proper and smooth way.

Test case scenarios: A rest client as a proxy of non native client (mjivita+) will post the same data json to the openSRP server of a particular house hold registration but may be with changing  some client attributes (i.e age, husband name ..). Next we will check that non native client (mjivita+) collections reflected at native client (openSRP client) ends.

Test Goals: 
Business Goals:
1. How sever keeping records dual version of data for same client?
2. Can it distinguish native providers data from non native provider data?
3. Can it link native provider data with non native provider data?
4. Can openSRP client properly retrieve and display non native providers submissions without any error or crush.

Technical Goals:
1. It will confirm input and output of each component parts. For example what non native client(mjivita+) should build before it submission? How native (FWA) and non native providers (FD) will link? How two version of data for a same client (woman) will tied? This will confirm interfacing and contract between different integration part. Which will then help to work in different part more independently and reduce chance of error after final integration.

Kindly everyone add your feedbacks/concern on its and confirm when we can run through this.

**Comment by ndisha** [comment]
@sohelsarder from our call on Tuesday, you have made great strides on this integration, am detailing what is remaining: 
* Ensure that you are using the latest code from OpenSRP master - that should help sort out the error you are facing when pushing to OpenMRS.
* The ELCOs from mJivita+ don't have a corresponding HH when data gets to OpenSRP
* Mapping providers with their data?
* Editing: the use case here is to allow a client to be captured using the OpenSRP client and to allow the record be edited through mjivita+

My goal is to make sure that we document where we are with this kind of integration; do we have the process documented as we go? Please share that with us.

**Comment by sohelsarder** [comment]
Hi, @ndisha thanks for detailing the issues and pending, we are still working with the aboves. we did check and found we are update with the master  but still data transmission failed to openmrs i think we need further checking to pin point where the exact problem persist. After data goes into openmrs that will complete the total cycle of external integration and the process as well i think then we can start process documentation.

**Comment by ndisha** [comment]
@sohelsarder since we have tested the newest code and submissions to OpenMRS are successful, can you test the integration with mJivita+, from end to end, and let us know if its working optimally? We need to know if this functionality is now completed.

**Comment by sohelsarder** [comment]
@ndisha yes we will run  a full cycle check by this week to confirm it.

**Comment by sohelsarder** [comment]
This feature is tested and deployed in production for mcare II
