### ISSUE TITLE
model.xml and formSubmission parser for attributes

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#33]
Parent #3 

Add a parser that 
- Reads properties from a FormSubmission 
- Finds model.xml binding in form_definition.json 
- Finds openmrs attributes associated with it for model.xml

So it allows to 
- query an attribute-value in X formSubmission for Y property (consider grouping and repeating groups)
- query a property name-value for X attribute in a FormSubmission

**Comment by maimoonak** [comment]
pseudo code for main method we would need to call
``` 
method: getAttributesForField (fieldName, formSubmission)

	formBindForField = getPropertyBindFromFormDefinition(fieldName, formSubmission); // From form_definition.json

	tagAndAttributes = getFormPropertyNameForAttribute(formBindForField); // xpath in model.xml

	Map <attribute,attributeValue> map from attributes in tagAndAttributes;

return attributes; 
```

**Comment by maimoonak** [comment]
Pseudo code for getPropertyBindFromFormDefinition
```
method: getPropertyBindFromFormDefinition(fieldName, formSubmission)
	read form_definition.json for given formSubmission from disk
	bindAttribute = get bind attribute for provided fieldName
return bindAttribute;
```

**Comment by maimoonak** [comment]
Pseudo code for getFormPropertyNameForAttribute
```
method: getFormPropertyNameForAttribute(formBindForField)
	read model.xml
	lastNode = use xpath for finding the path directly in the model.xml or split path by / and decend by each parent node unless last child specified is reached
return lastNode;
```

**Comment by wahid-nwr** [comment]
thanks maimoona

**Comment by maimoonak** [comment]
Thanks alot @wahid-nwr . The parser seem good. We also need the methods where we can find field name by attribute names and also by attribute name-value both.
Pseudo code for finding node with attribute name-value is below and once it is done it could be easily modified to find list of fields for specified attributes.

```
method: getFieldName (attributeMap<Map>, formSubmission)
	node = getNodeWithMatchingAttributes(attributeMap);
	fieldName =  getFieldNameWithPath(node.nodePath);
return fieldName; 

method: getNodeWithMatchingAttributes (attributeMap<Map>)
	//read model.xml
	foreach node in model.xml 
		foreach Entry in attributeMap if Entry.Key == node.AttributeName && attributeMap[node].Value == node.AttributeValue
			return node;
return null; 
```

**Comment by maimoonak** [comment]
Two more methods added to find value for specified attributeNam and also added a parser for getting concept id  for the select_one question selected option in formSubmission. This is done by parsing form.json for the form that is downloaded from Ona site. This json and xform are the only files those could be used to find mappings of concept ids for choices sheet.
