### ISSUE TITLE
Client Registration Export for PATH

### ISSUE THREAD

**Issue by mberg** [OpenSRP/opensrp-server#336]
## Registration Items

* Timestamp of registration
* Date of registration
* Provider ID / Health Worker Id
* ZEIR ID
* Child DOB
* Facility ID
* Facility Name
* Provider ID
* Place of Birth
	* Health Facility
	* Home
* Child's Residential Area

**Comment by claycrosby** [comment]
closing and moving to the ETL repo per meeting with Manu and Ephraim earlier:
https://github.com/OpenSRP/path-zambia-etl/issues/10
