### ISSUE TITLE
Set up OpenMRS dev instance

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#34]

**Comment by alihabib** [comment]
Setup is complete

Version: OpenMRS 1.9.7
URL: http://46.101.51.199:8080/openmrs

MVP dictionary has been installed.

Admin password and mysql authentication information are stored in /root/setup.txt on the server (it was the most secure place I could think of). @maimoonak or anyone else with root access: please pull this file from the server to see the credentials

Modules installed:
serialization Xstream	0.2.7
Reporting	                       0.9.3
HTML Form Entry	         2.5
HTML Form Entry Extensions for OpenMRS 1.9 Module	1.5
Rest Web Services	       2.8.19024
Calculation	               1.1
HTML Widgets	               1.6.7

I am now adding links to the OpenSRP Wiki to relevant OpenMRS installation guides

**Comment by maimoonak** [comment]
Thanks a bunch Ali. This is pretty much we needed for current sprint.

Thanks,
Maimoona
*Team Lead & Senior Software Engineer,*


*IHS - (Interactive Health Solutions)ww.ihsinformatics.com
<http://www.ihsinformatics.com>*
*Office - 92-213-4327697*

**Comment by alihabib** [comment]
Wiki page created: https://smartregister.atlassian.net/wiki/display/Documentation/OpenMRS+Installation
