### ISSUE TITLE
Rename all packages to org.opensrp from org.ei.drishti

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#4]
- Rename all packages in code to org.opensrp
- Rename artifacts to opensrp
- Rename properties files to opensrp from drishti

**Comment by julkarnain** [comment]
Ok, My packages and artifacts rename works is finished. Today i will merge your branch and rename the properties files also

**Comment by maimoonak** [comment]
The code is now in master branch
