### ISSUE TITLE
New Architecture of  OpenSRP backend regarding HouseHold registry

### ISSUE THREAD

**Issue by julkarnain** [OpenSRP/opensrp-server#41]
I am sharing the new structure of OpenSRP backend part. Please through some feedback and comments if anything missing or if we need to change the workflow diagram.

![opensrp_backend_class](https://cloud.githubusercontent.com/assets/1464868/7130271/0c024946-e28f-11e4-880b-02063db8486c.jpg)

**Comment by maimoonak** [comment]
@julkarnain looks good for now. Could you also sketch HH register in more detail. Also wouldbe very helpful if foreach section we can get a precise and very brief description.

**Comment by maimoonak** [comment]
@julkarnain Just wanted to get an update on this. I am planning to design a generic register interface in core. Do you have any thoughts on this. Is there anything missing or needs strong refactoring you encountered in exploring and creating this diagram? Did you take into account the possibility of Generic register instead of HH specific?

**Comment by julkarnain** [comment]
I will design the diagram more specific for mcare-II  but after the stable version otherwise I have change the design frequently

**Comment by ndisha** [comment]
@julkarnain, thanks for the wonderful work this past month!! Wanted to follow up on the brief description of the HH register architecture, that will wrap up this issue and greatly improve our documentation.

@sohelsarder @maimoonak

**Comment by maimoonak** [comment]
I think its all done.. Shouldnt we close it?

**Comment by ndisha** [comment]
Will close this and I will create a new issue in the new milestone for the opensrp class description to be done by @julkarnain
