### ISSUE TITLE
Interface for error resolution

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#43]
Parent #42 

- An interface for Viewing, Searching all errors
- Manual re-POST for errors resolved. As soon as error is resolved allow user/admin to re-post manually.
- Once posted successfully mark error as resolved.

**Comment by maimoonak** [comment]
Done!! and part of opensrp now

**Comment by shakjaf110** [comment]
[Update+ErrorTrace+Interface.docx](https://github.com/OpenSRP/opensrp-server/files/454764/Update.ErrorTrace.Interface.docx)

**Comment by shakjaf110** [comment]
[Update+ErrorTrace+Interface.docx](https://github.com/OpenSRP/opensrp-server/files/454765/Update.ErrorTrace.Interface.docx)
