### ISSUE TITLE
Documentation for OpenSRP server setup

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#45]
Write documentation for OpenSRP server code setup.  The documentation should 
- Start from scratch assuming a fresh OS installation.
- Should include every possible setup machine could require and also should point to respective setup of the software
- Should log all possible exceptions and their solutions
- Should include images wherever possible
- Should specify all files to change credentials in
- Should specify the steps clearly if anything needs to be created or setup in advance

@ndisha could you please coordinate with developer interested in working on this. I can provide my full support and guidance but dev would need to do it on a new machine with no development software installed to make sure that we explain every possible and minor thing in doc.

**Comment by ndisha** [comment]
@wahid-nwr @julkarnain @raufdesu @kercobo - mentioning you guys here to see if you are interested in this awesome task.. you can ping me privately or on here, its all good!

**Comment by julkarnain** [comment]
yes. I am interested to do this task yet i need time to complete and it will be step by step. I have to give extra efforts  and invest my personal time but no problem.

**Comment by ndisha** [comment]
Thanks @julkarnain no problem; we can assign you this task and you can coordinate with @maimoonak if you need any help.

**Comment by julkarnain** [comment]
Ok. Thanks. Sure if I face any problem.

**Comment by julkarnain** [comment]
@maimoonak  Can you please the OpenSRP windows installation process as well as OpenMRS installation guidance as I have heard Ali already wrote it. Just share both

**Comment by alihabib** [comment]
OpenMRS Installation info is on the OpenSRP Wiki at: https://smartregister.atlassian.net/wiki/display/Documentation/OpenMRS+Installation

**Comment by julkarnain** [comment]
Thanks Ali for sharing the location

**Comment by ndisha** [comment]
@julkarnain, thanks for the documentation you have done so far. Maimoona has worked on the contents, please see her comments here: https://docs.google.com/document/d/10miZ7hV-QG1s-Lm3h-awsjXZTxNVh3DlVmVW4lgznqQ/edit, for improvement of the content.

@sohelsarder

**Comment by ndisha** [comment]
This is also related to the OpenSRP class diagram work that is WIP from @julkarnain; so am closing this out.

**Comment by Rizwankmc** [comment]
> @wahid-nwr @julkarnain @raufdesu @kercobo - mentioning you guys here to see if you are interested in this awesome task.. you can ping me privately or on here, its all good!

i have a some issue on could u help me i have done all the things from scratch and on the time of creting .war file it shows some compilation error.
