### ISSUE TITLE
Data posting to shared health record system (SHR)

### ISSUE THREAD

**Issue by sohelsarder** [OpenSRP/opensrp-server#46]
In bangladesh, shared health record system is on of the potential candidate that want to receive submitted data from openSRP application. Internals/ API  of SHR is not officially finalized yet but assuming that it can post/get data through services very similar to openMRS API.  We need to find out integration point  inside openSRP server of that potential bottom layer client. From which point or order that transmission will initiate  (first: data save into couche, second: data transfer into openMRS, third: data transfer to SHR) and  who will do that shipment? Will openSRP connector will do that data transmission like currently it is doing into openMRS or other way?

**Comment by maimoonak** [comment]
@sohelsarder opensrp-connector name was chosen with the idea to integrate with multiple systems. Also All data is supposed to be in couch for sure and it would always by the first step.
Although a developer needs to extend it to make it integrable with SHR. One thing that we have to do for sure is mapping fields required by SHR with opensrp formSubmission. If you could give an example scenario we can provide detailed answer to this. 

Any thoughts from other members.
@mberg @djazayeri @alihabib @julkarnain @ndisha

**Comment by sohelsarder** [comment]
@mberg @djazayeri @alihabib @julkarnain @ndisha @maimoonak 
Last week I have discussion with anshuman from thoughtworks who is leading the team implementing SHR solution for Bangladesh about SHR integration with openSRP. There we have discussion about two choice of SHR integration.

Choice one: SHR integration directly from OpenSRP server similar to openSRP connector module  that SHR connector module with maintain the connection, field mapping and data transmission between SHR and openSRP. 

Pros: Reducing hoop, may be less error chance or delays(?).

Cons: It makes hard link over openSRP code base so any changes very specific to SHR will have always some sort of impact on openSRP. Also we will have less flexibility in portable sense with external application i.e mCare have integration requirement with SHR but other projects might not  have that requirements but both have to bear cost the legacy code.

Choice two: Let data pass into openMRS then a SHR client module will introduce in openMRS that will take care the connection, terminology mapping and data transmission between openMRS to SHR.

Pros: It is clear isolation of SHR integration code from openSRP code base so that will give the flexibility to enhance and modification there without affecting other parts of openSRP. Also give portable flexibility, if some one don't wants SHR integration (may be indonesia/ pakistan case) simply ignore that module.

Cons: Increase hoop, may be increase error chance or delays(?).

Please everyone add your thoughts over it.

**Comment by carlsbox** [comment]
I would like to weigh in and vote for option 2. This option would allow a
more interface and standards based approach (allows use of different
standards). Also this work could be leveraged and contributed to by the
larger OpenMRS community. there is some work under way around this idea (an
SHR link module for OpenMRS) although I'm not sure the quality and status
of this at the moment.

Tying OpenSRP to the Bangladesh Shared Health Record directly may make it
difficult to port to other areas later on.

Carl Fourie
---
*Assistant Director of Programs, Jembi Health Systems |  SOUTH AFRICA*
*Mobile: +27 71 540 4477 | Office: +27 21 701 0939 | Skype: carl.fourie17*
*E-mail: *carl.fourie@jembi.org

**Comment by alihabib** [comment]
Hi Sohel,

I'd go with Choice 2 so that we aren't forcing SHR-related code on to
implementations that don't need it and taking advantage of OpenMRS's
modular architecture to isolate the SHR piece. However, as part of our
roadmap, we are also planning to support EMR's (or databases) other than
OpenMRS down the road. In that instance if another EMR wants to connect to
an SHR, they would have to have their own SHR module implemented. This
isn't necessarily a bad thing but I'm flagging it to make sure that it is
recognized as an implication of Choice 2.

Ali

Ali Habib
Chief Executive Officer
Interactive Health Solutions
Ph: +92-21-34327697
ali.habib@irdresearch.org
http://www.irdresearch.org

**Comment by sohelsarder** [comment]
We have started update activities on this in another issue.
