### ISSUE TITLE
Document the different types of alerts

### ISSUE THREAD

**Issue by mberg** [OpenSRP/opensrp-server#47]
@ndisha work with @maimoonak to document the different type of events in OpenSRP

**Comment by maimoonak** [comment]
https://smartregister.atlassian.net/wiki/display/~maimoona.kausar/Scheduling+and+Schedule+tracking
Some of the documentation is here ... I would move it to OpenSRP Documentation space so that Ndisha can edit it.

**Comment by maimoonak** [comment]
Its here now..
https://smartregister.atlassian.net/wiki/display/Documentation/Scheduling+and+Schedule+tracking

**Comment by ndisha** [comment]
@mberg @maimoonak and I have added more information on the wiki, including scenarios for the alerts/reminders: https://smartregister.atlassian.net/wiki/display/Documentation/Scheduling+and+reminders+scenarios
