### ISSUE TITLE
Opensrp-core schedule redesign

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#48]
W.R.T. #12 
The approach of moving all scheduler code to opensrp-schedule to make it self contained separate independent module seems inappropriate because
- opensrp-schedule doesnot contain all logic for scheduling. Rather it contains few schedules classes with redundant logic and few classes for core scheduling.
- Despite some core code is in schedule it is still tightly coupled with core because Schedules and Action services and domain is a part of core logic and DB and to detach both is a hassle.
- It makes sense to add scheduling core to opensrp-core logic because all of the registers are supposed to be connected to any Schedule or Event in some way.

The idea is to provide core--scheduling code into opensrp-core and allow register developers to extend or use since schedules are to be instantiated fro register anyway

The code is was refactored without any change to actual design of system and the class diagram of the interactions b/w different components of system is as below

##### KEY for notations used 

![keyclassdiagram](https://cloud.githubusercontent.com/assets/4829880/7271237/7dcf8774-e8fb-11e4-9ccf-b755b2cfb3ab.png)

##### CURRENT system

![opensrpschedulingclassdia](https://cloud.githubusercontent.com/assets/4829880/7271187/355d2b7c-e8fb-11e4-960f-9ed7840c020d.png)

**Comment by maimoonak** [comment]
- The core was redesigned to reduce dependencies between classes and also reduce interaction between internal classes of scheduling module. Rather approach is to make all interaction through a boundary class SchedulerService. 
- The direct usage of external motech-scheduler API into classes directly interfacing with register specific code and classes those are supposed to be written by site developers are just dependent on SchedulerService
- Extra classes which were not required or should have been through a generic class have been introduced and instances handles the logic instead of separate class for similar type of action with different name (OpensrpEvent, RepeatingSchedule).
- Better, precise, and self explanatory names chosen for classes
Diagram with Proposed design is below

![opensrpproposedschedulingclassdia](https://cloud.githubusercontent.com/assets/4829880/7271574/cb7a847c-e8fd-11e4-906c-bec40ce66bb0.png)

**Comment by maimoonak** [comment]
On call with tech team there were some important questions raised and valuable suggestions given.
@djazayeri suggested to
- Rename SchedulerService to represent what type of schedule
- Create a cleaner separation of roles of Simple scheduled tasks or events and Trackable schedules, hence it led to two different services TaskScheduleService and HealthScheduleService
  - TaskScheduleService contains RepeatingSchedules and SystemEvents
  - HealthScheduleService has TrackableSchedules / HealthSchedules and Hooked Events

@mberg suggested to rename OpensrpEvent to SystemEvent

The new design for schedule-core is as below

![opensrpschedulingcoreclassdia](https://cloud.githubusercontent.com/assets/4829880/7272209/a6408d78-e902-11e4-8f84-d59da4179265.png)

An explanation of Types of schedules w.r.t. real world scenarios was found missing, specifically it was hard to understand which type of schedule applies to different events.

Below is each type mapped with real world scenarios. All examples in dev documentation would follow these scenarios to make sure that developer understand the schedule better @ndisha would map these with ANC and PNC and HH registers for Science team.

Consider a <b>DeathRegister</b> that handles info for deaths in a country.

###### RepeatingSchedule:
In web system we need a service that everyday at 12am (to prevent server load on peak times)
- Sends an email with CSV of records to data admins with different inconsistencies in data like DeathDate not matches with other data, OR Any symptom not valid for gender or age group
- Do cleanup operations on server
And many more which could be repeated with a fixed delay and fixed repeat delay and this is <b>"RepeatingSchedule"</b>

###### SystemEvent:
We have many other registers not directly connected with eachother which needs to take decisions based on any Death like ANC/PNC on mother death, Child on foetal / infant death, Crime investigation on Accidental death, TrendResearcher on death by disease etc. We can not maintain logic in a single central point maintain by central developer modifying everytime a new decision is needed based on death. Rather we notify system with deathEvent and each register implementing Listeners for Death notification would do their work independantly. This is <b>"SystemEvent"</b>

###### TrackableSchedule:
Lets say each death has to be enrolled in different types of schedules with different milestones and alert for FieldWorkers like each death notification would lead to an enrollment into schedule starting after 20days of death for a VerbalAutopsy and VA has to be completed within 60days. ANM after contacting relatives needs to fill VA before 60th day as this s MAX timeWindow. Also an accidental death would schedule alerts for Investigation for Opening case and Closing within 2years the last month of 2nd year is the MAX timeWindow for this.
These schedules which have different milestones and different timeWindows with different Alerts are <b> "TrackableSchedule" or "HealthSchedule"</b>

###### HookedEvent:
Now there could be different institution Registers in Country which want to get notified or run thert logic when a certain timeWindow or milestone alert is notified. For ex: Police wants to get an alert when a case has not been closed until the end of 2nd year of Opening and CrimeResearch Register also want an alert when case has not been closed within 2n years. There could be 3rd , 4th and 5th Registers which want notification on passing some schedule`s timeWindow. One register dev can not keep adding logic to this. Now we need to hook an event to DeathCaseClosing schedule so that different systems could be alert of certain milestones timeWindows. This would be done by Register dev by implementing a <b>"HookedEvent"</b> with schedule DeathCaseClosing, milestone LastQuarter, and timeWindow MAX

**Comment by maimoonak** [comment]
Documentation for the component is here and would be kept updated as we go on

**Comment by ndisha** [comment]
@maimoonak I have copied these scenarios and some more examples on the wiki. We might need to work to remove the repetitions that I have possibly created!

**Comment by maimoonak** [comment]
Done, pull request merged with master. 
Developer documentation is available here https://smartregister.atlassian.net/wiki/display/Documentation/Scheduling+and+Schedule+tracking
