### ISSUE TITLE
Add growth chart module to central OpenMRS dev instance

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#61]
https://wiki.openmrs.org/display/docs/Growth+Chart+Module

This is for exploration and testing to see if it meets our needs for growth charts and nutrition register.

**Comment by ndisha** [comment]
This is done - development work to extend it will be started once V2 development priorities are finalized.

**Comment by cagulas** [comment]
Thanks so much @ndisha!  Will check it out.
