### ISSUE TITLE
Services are needed in OpenSRP for data mapping from FD to FWA in mJivita+ integration 

### ISSUE THREAD

**Issue by julkarnain** [OpenSRP/opensrp-server#62]
For mJivita+ integration, mJivita+ application needs some informations from OpenSRP. OpenSRP needs to provide two services for mapping FD data to FWA. 

1. getEntityIdForBRN(String womanBRN) : mJivita+ will invoke the service providing woman BRN id and service will return entityId of the HH submission data set because brn id will be unique for mJivita+ and OpenSRP . mJivita+ will wrap up the entityId in its submission preparing. mJivita+ submission will also add the usertype tag i.e fd so that we can find out the difference between fd and fwa data set. 

2. getProviderIdForLocationName(String mauzaPara) : mJivita+ will provide mauzapara and OpenSRP returns anmId/providerId. This call would need OpenMRS rest call to get the user by location. Then mJivita+ will edit the providerId to the submission so that FD to FWA mappings perform properly.

**Comment by maimoonak** [comment]
@julkarnain I remember you were working on this, or someone else is supposed to be assigned to it. Is it part of mcare server code!? If yes, we need to bring it into core master repo!

**Comment by ndisha** [comment]
@julkarnain @sohelsarder from the demo we saw on the progress on work done in the mJivita+ integration with OpenSRP, is this now done? Is there a branch where this is being done on the OpenSRP repo?

**Comment by julkarnain** [comment]
@ndisha  @maimoonak Service getEntityIdForBRN is done It had not any dependency. BUT service getProviderIdForLocationName is invoking OpenMRS rest call . There need username by locationname. Safwan worked in team management module for the service  but in team management module the person has full name not user name. We need username for FD and FWA mapping. 

I have informed Safwan but i dont know he made sense or not

**Comment by maimoonak** [comment]
@MuhammadSafwan please also add user data to the object returned by REST service for team member by location. This would lead to finding User data in DB having personId mapped by team member and returning it with response as property "user". If it has already been implemented please share the final output by REST web service and if there is any confusion let me know.
EX: getTeamMemeberByLocation = Pakistan
- Find Team members in Pakistan
- Foreach member find Person by personId of TeamMember
- Foreach member also find User by personId of TeamMember
So final response would contain
- teamMember
- location
- provider
- person
- user

**Comment by julkarnain** [comment]
@MuhammadSafwan 
The output of the rest call . I could not find the personId here

{"results":[{"teamMemberId":6,"identifier":"9892392","isTeamLead":false,"person":{"uuid":"23f56e82-ed2b-433a-8cad-de42b94c39e6","display":"badal sagar","gender":"Male","age":null,"birthdate":null,"birthdateEstimated":false,"dead":false,"deathDate":null,"causeOfDeath":null,"preferredName":{"uuid":"004cb514-f738-4bfb-bc2b-57b04af63be1","display":"badal sagar","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/person/23f56e82-ed2b-433a-8cad-de42b94c39e6/name/004cb514-f738-4bfb-bc2b-57b04af63be1","rel":"self"}]},"preferredAddress":null,"attributes":[],"voided":false,"links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/person/23f56e82-ed2b-433a-8cad-de42b94c39e6","rel":"self"},{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/person/23f56e82-ed2b-433a-8cad-de42b94c39e6?v=full","rel":"full"}],"resourceVersion":"1.8"},"uuid":"327e0810-2856-4a6d-b07d-0a53e2bafd52","location":[{"uuid":"cd4ed528-87cd-42ee-a175-5e7089521ebd","display":"Pakistan","name":"Pakistan","description":"fbdjjj","address1":null,"address2":null,"cityVillage":null,"stateProvince":null,"country":null,"postalCode":null,"latitude":null,"longitude":null,"countyDistrict":null,"address3":null,"address4":null,"address5":null,"address6":null,"tags":[{"uuid":"9ab943d7-efc5-4583-8fd7-d645e48ec538","display":"Country","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/locationtag/9ab943d7-efc5-4583-8fd7-d645e48ec538","rel":"self"}]}],"parentLocation":null,"childLocations":[{"uuid":"461f2be7-c95d-433c-b1d7-c68f272409d7","display":"Sindh","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/461f2be7-c95d-433c-b1d7-c68f272409d7","rel":"self"}]}],"retired":false,"attributes":[],"links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/cd4ed528-87cd-42ee-a175-5e7089521ebd","rel":"self"},{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/cd4ed528-87cd-42ee-a175-5e7089521ebd?v=full","rel":"full"}],"resourceVersion":"1.9"}],"team":{"display":"FWA","teamIdentifier":"0001","teamName":"FWA","uuid":"db5d0150-1599-44f2-badb-25f0433ae8b7","dateCreated":"2015-05-10T08:36:26.000-0400","location":{"uuid":"bfeb65bd-bff0-41bb-81a0-0220a4200bff","display":"Ward-1","name":"Ward-1","description":null,"address1":null,"address2":null,"cityVillage":null,"stateProvince":null,"country":null,"postalCode":null,"latitude":null,"longitude":null,"countyDistrict":null,"address3":null,"address4":null,"address5":null,"address6":null,"tags":[{"uuid":"f20f5409-0320-48c8-bf12-85031d59f215","display":"Ward","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/locationtag/f20f5409-0320-48c8-bf12-85031d59f215","rel":"self"}]}],"parentLocation":{"uuid":"725658c6-4d94-4791-bad6-614dec63d83b","display":"KUPTALA","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/725658c6-4d94-4791-bad6-614dec63d83b","rel":"self"}]},"childLocations":[{"uuid":"42423d74-a061-463b-93a1-2f773f0aae21","display":"1-KA","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/42423d74-a061-463b-93a1-2f773f0aae21","rel":"self"}]},{"uuid":"429feb8b-0b8d-4496-8e54-fdc94affed07","display":"1-KHA","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/429feb8b-0b8d-4496-8e54-fdc94affed07","rel":"self"}]}],"retired":false,"attributes":[],"links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/bfeb65bd-bff0-41bb-81a0-0220a4200bff","rel":"self"},{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/bfeb65bd-bff0-41bb-81a0-0220a4200bff?v=full","rel":"full"}],"resourceVersion":"1.9"},"memberCount":null,"resourceVersion":"1.8"},"resourceVersion":"1.8"},{"teamMemberId":12,"identifier":"1111111","isTeamLead":false,"person":{"uuid":"ee2d968f-c24c-408e-a7e1-7f32808a54a9","display":"sagar sahil","gender":"Male","age":null,"birthdate":null,"birthdateEstimated":false,"dead":false,"deathDate":null,"causeOfDeath":null,"preferredName":{"uuid":"bbf202b1-0b6c-4b24-9526-6d1190781385","display":"sagar sahil","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/person/ee2d968f-c24c-408e-a7e1-7f32808a54a9/name/bbf202b1-0b6c-4b24-9526-6d1190781385","rel":"self"}]},"preferredAddress":null,"attributes":[],"voided":false,"links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/person/ee2d968f-c24c-408e-a7e1-7f32808a54a9","rel":"self"},{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/person/ee2d968f-c24c-408e-a7e1-7f32808a54a9?v=full","rel":"full"}],"resourceVersion":"1.8"},"uuid":"c89d9182-26ac-4491-9895-72d58caf7b9c","location":[{"uuid":"cd4ed528-87cd-42ee-a175-5e7089521ebd","display":"Pakistan","name":"Pakistan","description":"fbdjjj","address1":null,"address2":null,"cityVillage":null,"stateProvince":null,"country":null,"postalCode":null,"latitude":null,"longitude":null,"countyDistrict":null,"address3":null,"address4":null,"address5":null,"address6":null,"tags":[{"uuid":"9ab943d7-efc5-4583-8fd7-d645e48ec538","display":"Country","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/locationtag/9ab943d7-efc5-4583-8fd7-d645e48ec538","rel":"self"}]}],"parentLocation":null,"childLocations":[{"uuid":"461f2be7-c95d-433c-b1d7-c68f272409d7","display":"Sindh","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/461f2be7-c95d-433c-b1d7-c68f272409d7","rel":"self"}]}],"retired":false,"attributes":[],"links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/cd4ed528-87cd-42ee-a175-5e7089521ebd","rel":"self"},{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/cd4ed528-87cd-42ee-a175-5e7089521ebd?v=full","rel":"full"}],"resourceVersion":"1.9"},{"uuid":"429feb8b-0b8d-4496-8e54-fdc94affed07","display":"1-KHA","name":"1-KHA","description":null,"address1":null,"address2":null,"cityVillage":null,"stateProvince":null,"country":null,"postalCode":null,"latitude":null,"longitude":null,"countyDistrict":null,"address3":null,"address4":null,"address5":null,"address6":null,"tags":[{"uuid":"413c6c3e-e2f7-4204-8da5-b204c5b00477","display":"Unit","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/locationtag/413c6c3e-e2f7-4204-8da5-b204c5b00477","rel":"self"}]}],"parentLocation":{"uuid":"bfeb65bd-bff0-41bb-81a0-0220a4200bff","display":"Ward-1","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/bfeb65bd-bff0-41bb-81a0-0220a4200bff","rel":"self"}]},"childLocations":[{"uuid":"9047a5e3-66cf-4f83-b0b6-3cdd3d611272","display":"Chapadaha Mauza","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/9047a5e3-66cf-4f83-b0b6-3cdd3d611272","rel":"self"}]},{"uuid":"a8b7d760-0e7e-4fdb-9450-b41d31d1ec34","display":"Kuptala-1-KHA","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/a8b7d760-0e7e-4fdb-9450-b41d31d1ec34","rel":"self"}]}],"retired":false,"attributes":[],"links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/429feb8b-0b8d-4496-8e54-fdc94affed07","rel":"self"},{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/429feb8b-0b8d-4496-8e54-fdc94affed07?v=full","rel":"full"}],"resourceVersion":"1.9"},{"uuid":"42423d74-a061-463b-93a1-2f773f0aae21","display":"1-KA","name":"1-KA","description":null,"address1":null,"address2":null,"cityVillage":null,"stateProvince":null,"country":null,"postalCode":null,"latitude":null,"longitude":null,"countyDistrict":null,"address3":null,"address4":null,"address5":null,"address6":null,"tags":[{"uuid":"413c6c3e-e2f7-4204-8da5-b204c5b00477","display":"Unit","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/locationtag/413c6c3e-e2f7-4204-8da5-b204c5b00477","rel":"self"}]}],"parentLocation":{"uuid":"bfeb65bd-bff0-41bb-81a0-0220a4200bff","display":"Ward-1","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/bfeb65bd-bff0-41bb-81a0-0220a4200bff","rel":"self"}]},"childLocations":[{"uuid":"88abc9f1-d698-41e3-8e2d-0c900b16dfe6","display":"Kuptala-1-KA","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/88abc9f1-d698-41e3-8e2d-0c900b16dfe6","rel":"self"}]}],"retired":false,"attributes":[],"links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/42423d74-a061-463b-93a1-2f773f0aae21","rel":"self"},{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/42423d74-a061-463b-93a1-2f773f0aae21?v=full","rel":"full"}],"resourceVersion":"1.9"}],"team":{"display":"FWA","teamIdentifier":"0001","teamName":"FWA","uuid":"db5d0150-1599-44f2-badb-25f0433ae8b7","dateCreated":"2015-05-10T08:36:26.000-0400","location":{"uuid":"bfeb65bd-bff0-41bb-81a0-0220a4200bff","display":"Ward-1","name":"Ward-1","description":null,"address1":null,"address2":null,"cityVillage":null,"stateProvince":null,"country":null,"postalCode":null,"latitude":null,"longitude":null,"countyDistrict":null,"address3":null,"address4":null,"address5":null,"address6":null,"tags":[{"uuid":"f20f5409-0320-48c8-bf12-85031d59f215","display":"Ward","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/locationtag/f20f5409-0320-48c8-bf12-85031d59f215","rel":"self"}]}],"parentLocation":{"uuid":"725658c6-4d94-4791-bad6-614dec63d83b","display":"KUPTALA","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/725658c6-4d94-4791-bad6-614dec63d83b","rel":"self"}]},"childLocations":[{"uuid":"42423d74-a061-463b-93a1-2f773f0aae21","display":"1-KA","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/42423d74-a061-463b-93a1-2f773f0aae21","rel":"self"}]},{"uuid":"429feb8b-0b8d-4496-8e54-fdc94affed07","display":"1-KHA","links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/429feb8b-0b8d-4496-8e54-fdc94affed07","rel":"self"}]}],"retired":false,"attributes":[],"links":[{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/bfeb65bd-bff0-41bb-81a0-0220a4200bff","rel":"self"},{"uri":"NEED-TO-CONFIGURE/ws/rest/v1/location/bfeb65bd-bff0-41bb-81a0-0220a4200bff?v=full","rel":"full"}],"resourceVersion":"1.9"},"memberCount":null,"resourceVersion":"1.8"},"resourceVersion":"1.8"}]}

**Comment by MuhammadSafwan** [comment]
@Julkar if there is person uuid, you can find personId by it. The person
object is added so that some detail associated with it is returned.


MUHAMMAD SAFWAN
Software Engineer
Interactive Health Solutions
www.ihsinformatics.com

**Comment by julkarnain** [comment]
@MuhammadSafwan from which class i can find the personId . I mean where i will send request with uuid

**Comment by MuhammadSafwan** [comment]
@Julkar you can find the person by using openmrs api's method:
Context.getPersonService().getPersonByUuid(uuid);

You'll get the person object and then you can find id by:
person.getId();

You will have to include the Context api.


MUHAMMAD SAFWAN
Software Engineer
Interactive Health Solutions
www.ihsinformatics.com

**Comment by julkarnain** [comment]
@MuhammadSafwan Please give me the url by which i can get the person . I have tried with
http://46.101.51.199:8080/openmrs/ws/rest/v1/person?v=full&uuid=23f56e82-ed2b-433a-8cad-de42b94c39e6" but do not get the person

**Comment by maimoonak** [comment]
@Julkar person is available with complete details in the JSON you shared.
Te json path is results[0].person Or results[1].person.



Thanks,
Maimoona
*Team Lead & Senior Software Engineer,*


*IHS - (Interactive Health Solutions)ww.ihsinformatics.com
<http://www.ihsinformatics.com>*
*Office - 92-213-4327697*

**Comment by maimoonak** [comment]
@MuhammadSafwan The work is to access data only and only by REST. We dont have access to OpenMRS API and we donot want it accessible in OpenSRP

**Comment by maimoonak** [comment]
@MuhammadSafwan The request still doesnot contain user info for the person. Is it under progress?

**Comment by julkarnain** [comment]
@MuhammadSafwan Here is the query example that I am expecting to you. Execute it in openmrs database sql editor, you can see the output

SELECT u.username,t.name,m.person_id FROM openmrs.location as l 
INNER JOIN openmrs.team as t
on  l.location_id =t.location_id 
INNER JOIN openmrs.team_member as m
on t.team_id = m.team_id
INNER JOIN openmrs.users as u
on m.person_id = u.person_id
 where l.name ='sarderpara';

**Comment by MuhammadSafwan** [comment]
@Julkar I didn't understand what exactly is required. Is it username or
person? If it's person then kindly refer to Maimoona's email which says:
@Julkar person is available with complete details in the JSON you shared.
The json path is results[0].person Or results[1].person.

Thanks,


MUHAMMAD SAFWAN
Software Engineer
Interactive Health Solutions
www.ihsinformatics.com

**Comment by julkarnain** [comment]
@MuhammadSafwan  ofcourse username. I said  several times

**Comment by MuhammadSafwan** [comment]
@Julkar the ONA test server(http://46.101.51.199:8080/openmrs) has been
updated with the rest call in which there is username too.

Thanks,
MUHAMMAD SAFWAN
Software Engineer
Interactive Health Solutions
www.ihsinformatics.com

**Comment by sohelsarder** [comment]
Hi Safwan,


Can you please write the steps/ guidelines so that other openmrs instance could facilitate the same service.




Thanks,


[Business card] Sohel Sarder
Software Development Lead
M: +8801711082537
E: sohel@mpower-social.com


[http://imroz-bd.com/wp-content/uploads/2014/10/mPower-logo3.png]
[http://imroz-bd.com/wp-content/uploads/2014/10/facebook.png]<https://www.facebook.com/mPowerSocial> [http://imroz-bd.com/wp-content/uploads/2014/10/twitter.png] <https://twitter.com/mPowerSoc>  [http://imroz-bd.com/wp-content/uploads/2014/10/vimeo.png] <http://vimeo.com/mpowersocial>  [http://imroz-bd.com/wp-content/uploads/2014/10/youtube.png] <https://www.youtube.com/user/mPowerSocial>  [http://imroz-bd.com/wp-content/uploads/2014/10/website.png] <http://www.mpower-social.com>

mPower Social Enterprises Ltd.
H # 133 | R# 4 | B # A | Banani | Dhaka-1213 |
Phone: +88 02 9851 598


________________________________

**Comment by MuhammadSafwan** [comment]
Hi Sohel,

- To url to find members via location is:

           /openmrs/ws/rest/v1/teammodule/memberLocation?q=Georgia&v=full

(Georgia is to be replaced with the location.)

- Then the rest call will bring two objects:

          - Team Member
          - User

Team Member object will contain information about team member i.e.
memberId, team of member, uuid, person etc.
User object will contain information about userId, uuid, username, systemId
etc.

Please note that if the member is not a user then it will be null.


Thanks,
MUHAMMAD SAFWAN
Software Engineer
Interactive Health Solutions
www.ihsinformatics.com

**Comment by sohelsarder** [comment]
Hi Safwan,
Thanks, that's great you wrote service descriptions but what I need to know if other openmrs  instance want to provide same services what we need do, did you modified  team management module that's update we need to install or what else we have to do?

Thanks,
sohel

 Muhammad Safwan <notifications@github.com> wrote:



Hi Sohel,

- To url to find members via location is:

/openmrs/ws/rest/v1/teammodule/memberLocation?q=Georgia&v=full

(Georgia is to be replaced with the location.)

- Then the rest call will bring two objects:

- Team Member
- User

Team Member object will contain information about team member i.e.
memberId, team of member, uuid, person etc.
User object will contain information about userId, uuid, username, systemId
etc.

Please note that if the member is not a user then it will be null.


Thanks,
MUHAMMAD SAFWAN
Software Engineer
Interactive Health Solutions
www.ihsinformatics.com

On Tue, Sep 1, 2015 at 2:42 PM, Sohel Sarder <notifications@github.com>
wrote:

> Hi Safwan,
>
>
> Can you please write the steps/ guidelines so that other openmrs instance
> could facilitate the same service.
>
>
>
>
> Thanks,
>
>
> [Business card] Sohel Sarder
> Software Development Lead
> M: +8801711082537
> E: sohel@mpower-social.com
>
>
> [http://imroz-bd.com/wp-content/uploads/2014/10/mPower-logo3.png]
> [http://imroz-bd.com/wp-content/uploads/2014/10/facebook.png]<
> https://www.facebook.com/mPowerSocial> [
> http://imroz-bd.com/wp-content/uploads/2014/10/twitter.png] <
> https://twitter.com/mPowerSoc> [
> http://imroz-bd.com/wp-content/uploads/2014/10/vimeo.png] <
> http://vimeo.com/mpowersocial> [
> http://imroz-bd.com/wp-content/uploads/2014/10/youtube.png] <
> https://www.youtube.com/user/mPowerSocial> [
> http://imroz-bd.com/wp-content/uploads/2014/10/website.png] <
> http://www.mpower-social.com>
>
> mPower Social Enterprises Ltd.
> H # 133 | R# 4 | B # A | Banani | Dhaka-1213 |
> Phone: +88 02 9851 598
>
>
> ________________________________
> From: Muhammad Safwan <notifications@github.com>
> Sent: Tuesday, September 1, 2015 3:30 PM
> To: OpenSRP/opensrp-server
> Cc: Sohel Sarder
> Subject: Re: [opensrp-server] Services are needed in OpenSRP for data
> mapping from FD to FWA in mJivita+ integration (#62)
>
> @Julkar the ONA test server(http://46.101.51.199:8080/openmrs) has been
> updated with the rest call in which there is username too.
>
> Thanks,
> MUHAMMAD SAFWAN
> Software Engineer
> Interactive Health Solutions
> www.ihsinformatics.com
>
> On Mon, Aug 31, 2015 at 1:07 PM, Julkar Nain <notifications@github.com>
> wrote:
>
> > @MuhammadSafwan <https://github.com/MuhammadSafwan> ofcourse username. I
> > said several times
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/OpenSRP/opensrp-server/issues/62#issuecomment-136296205
> >
> > .
> >
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/OpenSRP/opensrp-server/issues/62#issuecomment-136648484
> >.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSRP/opensrp-server/issues/62#issuecomment-136651255>
> .
>

-

**Comment by ndisha** [comment]
@MuhammadSafwan it seems @julkarnain and @sohelsarder still required something from you! Or was this concluded? @maimoonak?

**Comment by sohelsarder** [comment]
These services are integrated and used in mcare 2.
