### ISSUE TITLE
OpenSRP API

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#9]
@mberg , @djazayeri , @alihabib  , @ndisha , @raihan-mpower , @julkarnain , @sohelsarder , @jayantchaudhari7 , @gigix , @cagulas , @dimasciput , @raufdesu , @kercobo , @wahid-nwr 

Create project opensrp-api that provides:

1) Domain objects for 
- <b>Client:</b> clientId{unique}, firstName, lastName, birthdate, deathdate, birthdateApprox, deathdateApprox, gender {male,female,MTF,FTM,unknown}, addresses[addressType,isActive, startDate, endDate, otherAttributes….], identifiers[idType, isActive, identifier….], attributes[key-value]
- <b>User:</b> username{unique}, password, salt, status, roles[name, permissions[]],  
- <b>Location:</b> name, address[country,city,town,state,province,county,village, otherAttributes], identifier, isActive, parentLocation, tags[name], attributes[key-value]
- <b>Provider:</b> [Replacement of ANM; Do we need separate Provider?]
- <b>Event and Obs:</b> [Do we need these if we would get concepts inside FormSubmission]
- <b>FormSubmission:</b> [If we are getting rid of Event&Obs]
- Note: All entities must have audit data like creator, editor, dateCreated, dateEdited, voided, voidReason
- Note: Nested entities could be separate POJOs. But these wold not exists in DB as separate entity
- <i>I am not sure how it could be handled but exploring the drishti data I assume that everything in opensrp revolves around Service [What is a service that needs explanation] like FP, ANC, PNC, Immunization are services provided by local bodies. Can we add service as an entity that would have properties and every register/form may mention the service it provides. Based on this we can generate schedules/Alerts/Reminders. We can then based on the service can generate reports too..</i>

2) Interface/Contract for 
- <b>Data Manager:</b> Min functionality required for Client data like by location, provider, dates, forms, etc]
- <b>SecurityManager:</b>
 * getRolesAndPersmissions{for specified user}, 
 * authenticate{specified user}, 
 * verifyAuthorization{for specified user and privilege and/or location}, 
 * encryption{for data to be transmitted},  
 * encryption{for user password}, 
 * decryption{for data received}, 
 * Note: User passwords should be hashed i.e. non-decryptable
- <b>LocationManager:</b>
 * GetLocation
 * GetAncestry{for specified location}
 * GetChildren{for specified location}
 * VerifyLocationAccess
 * Note: Each location would have a location id that can be linked in its child locations.

3) Common Utils and Constants for OpenSRP core those would be required or sure by Client system and web-server as well

Implementation of "API: Uniform across the system" of document https://docs.google.com/a/ihsinformatics.com/document/d/1jtlRJe37jSyZUvDJ97m3ZlKJqCuPiZTNSrjS7ywzec8/edit

**Comment by maimoonak** [comment]
I was trying to explore code more and found out the reason why drishti had too many mappers, wrappers and converters. They are using Motech DAO for couch data access and this bound entities to extend MotechBaseDataObject and this is a blocker in the approach we have chosen for API. There are two possible things we can do. Implement an API and their DTO/interface layer would be removed. The approach they use for their repository access would remain same. This can be seamlessly changed in future if we want to. Other approach would be changing the data access layer now but we may miss important aspects which can cause problem later on.
Since API is the first thing we need and this is proving to be a blocker for nearly everything in refactoring, I am working on it and based on other devs input we can refactor it later on.

**Comment by mberg** [comment]
Hi Maimoona,

Few questions.  Can you explain the difference between Event & Obs and FormSubmission?  

I like the idea of keeping event and obs.  I'm not sure how it relates to FormSubmission.  Can you elaborate a bit.

On location, what does GetAncestry mean?  Is this like get parent?


GetAncestry{for specified location}

**Comment by mberg** [comment]
@maimoonak are the client properties defaults from OpenMRS?

**Comment by maimoonak** [comment]
<b>GetAncestry{for specified location}</b>
Apologies for the mistake: This is getLocationHierarchy{startingLocationId}

<b>difference between Event & Obs and FormSubmission?</b>
Probably I can not perceive Event and Obs you have in mind. The Event and Obs like model in OpenMRS maps to a relational model where Event is stored separately and Obs are stored in a separate table with a referenceId of the Event. But our model is Couch so Event would have all Obs embedded inside the document means that only Event would persist in DB with Obs array embedded inside. Now on the other hand our FromSubmission (with name, value) is exactly similar to the structure we would have for Event (concept,value). Darius mentioned that Obs would have concept_id and parent_concept_id too along with other info, but now when we are working to embed all this info inside FormSubmission why we need same entities with different name. What would be difference between Event&Obs and Formsubmission. Logically both are far different but I can not understand the architectural difference for our app.

<b>are the client properties defaults from OpenMRS?</b>
Not sure if I got it correctly, but the GlobalProperties would be common properties b/w client and server those need to be changed on the fly.

**Comment by ndisha** [comment]
@maimoonak same case here - there is a great chunk of work that has been completed here, can we further split this and close what is done and keep only what is pending open?

**Comment by maimoonak** [comment]
A very shallow view of API is in the diagram

![opensrp-api](https://cloud.githubusercontent.com/assets/4829880/7368265/cd846852-edbf-11e4-9787-089bfd21a200.png)

**Comment by maimoonak** [comment]
Self answered few questions
- Provider implemented
- Event and Obs implemented (thanks to @djazayeri for explaining it in detail on call)
- FormSubmission implemented and each event would link back to form submission

The detailed class diagram of API is below

![opensrp-apiclassdiag](https://cloud.githubusercontent.com/assets/4829880/7368796/36d31876-edc5-11e4-9bfc-f99c49a03a55.png)

**Comment by ndisha** [comment]
@maimoonak is https://github.com/OpenSRP/opensrp-server/issues/38 catered for here as well? I see in the diagram, the events, obs and form_submission included therefore was wondering if this is by extension closed?

**Comment by maimoonak** [comment]
Both issues are very different and i can not trace where and how both are linked. Also the issue is linked with 3, the functionality is there but not well tested on a real working register so should not be closed until first release. If there are any other queries please discuss on hipchat or email.
