### ISSUE TITLE
Extend OpenMRS connector to handle observation repeat groups

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#92]
As discussed during PK science call today, OpenMRS connector needs to handle repeat groups for observations.

@maimoonak assigning to you.  Pls let me know what you use for entity and entity id, so that I can update the data mapping protocol appropriately.

**Comment by asifur77** [comment]
@maimoonak: Can you give me update on OpenMRS connector to handle repeat groups for observations?

{
 "obs": [
   {
     "concept": "148834AAAAAAAAAAAAAAAAAAAAAAAAAA",
     "groupMembers": [
       {
         "concept": "1729AAAAAAAAAAAAAAAAAAAAAAAAAAAA",
         "value": "1066AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
       }
     ]
   },
 ]
}

**Comment by asifur77** [comment]
@maimoonak: Can you give me update on OpenMRS connector to handle repeat groups for observations?

{
 "obs": [
   {
     "concept": "148834AAAAAAAAAAAAAAAAAAAAAAAAAA",
     "groupMembers": [
       {
         "concept": "1729AAAAAAAAAAAAAAAAAAAAAAAAAAAA",
         "value": "1066AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
       }
     ]
   },
 ]
}

**Comment by maimoonak** [comment]
Repeat groups for OBS are not allowed for same type of entity. Though subforms/repeat groups for child entities are allowed and work fine.. The snippet shared above should work fine if concept mappings are correct and following mapping protocol

**Comment by sohelsarder** [comment]
hey maimoonak can you please send us the branch name where that code updated that could handle repeat group case it may be chances we have to update our openmrs connector module that may be missing that enhancement.

**Comment by maimoonak** [comment]
Master branch has latest code for repeat group handling for multiselect and repeats for child entities.

**Comment by cagulas** [comment]
@maimoonak so repeats are only allowed for child entities?  I thought observation repeat group for same entity was PK requirement for vaccine stock form?

**Comment by sohelsarder** [comment]
It  seems multiselect data handling was missing at our branch and the same way we could not handle over our code.  We incorporated that missing to our code, after testing we are going to confirm it.

**Comment by sohelsarder** [comment]
This issue fixed in mcare-2 branch.
