### ISSUE TITLE
Difference in patient image in OpenMRS patient image module

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#95]
Why do some patients show this default patient image:

![screen shot 2015-10-19 at 5 24 35 pm](https://cloud.githubusercontent.com/assets/3488986/10591857/88b90caa-7686-11e5-8786-c9bdf84c3cbe.png)

While others show this:

![screen shot 2015-10-19 at 5 24 17 pm](https://cloud.githubusercontent.com/assets/3488986/10591863/9151532c-7686-11e5-93b2-76cdd1c49ca5.png)

**Comment by ahmedihs** [comment]
i am fixing this bug .  will be done in next version

**Comment by cagulas** [comment]
Ok, great.

**Comment by cagulas** [comment]
@ahmedihs This still doesn't seem fixed:

![screen shot 2016-01-29 at 9 57 46 am](https://cloud.githubusercontent.com/assets/3488986/12678859/ea86662a-c66e-11e5-803e-16b32a649203.png)

**Comment by ahmedihs** [comment]
![issue 95 resolved](https://cloud.githubusercontent.com/assets/11191881/12695702/5893f01a-c778-11e5-9e45-cf7418a7900c.PNG) @cagulas  this issue has been resolved . please check it on the server . code is uploaded to patient image module in imageupload branch .

**Comment by cagulas** [comment]
Thanks, I can confirm it's fixed.  Can this branch be merged into master now?

**Comment by ahmedihs** [comment]
I have created pull request . on this [repo ](https://github.com/OpenSRP/openmrs-module-patientimage)

**Comment by cagulas** [comment]
Closed with https://github.com/OpenSRP/openmrs-module-patientimage/pull/1
